### ISSUE TITLE
compatibilyTraitlets 5.0

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#140]
**Describe the bug**
Traitlets 5.0 leads to an error at scpy import 
 
**To Reproduce**
run scpy with Traitlets 5.0. wich has removed class_of(), see https://traitlets.readthedocs.io/en/stable/changelog.html

Pycharm debugger output:

Loading SpectroChemPy API:   8%|▊         | 92/1211 [00:00<01:08, 16.39it/s]Traceback (most recent call last):
  File "C:\Users\Arnaud\Dropbox\Programmes\spectrochempy\spectrochempy\utils\file.py", line 347, in generate_api
    pkg = import_item(pkg)
  File "C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\utils\importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
  File "C:\Users\Arnaud\Dropbox\Programmes\spectrochempy\spectrochempy\core\dataset\ndcoordrange.py", line 16, in <module>
    from traitlets import (HasTraits, List, Bool, TraitError, class_of)
ImportError: cannot import name 'class_of' from 'traitlets' (C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\__init__.py)

**Expected behavior**
scpy should preferentiall work with both version of traitlets (4 and 5) or 5 only.

**Comment by atravert** [comment]
provisional fix: https://github.com/atravert/spectrochempy/commit/e368030dd6a61631db3376e525c87a2a6aa294d9

works fine with traitlets  4 a 5. But the output with traitlets 5.0 is strange (try  CoordRange((1,2,3)))

**Comment by fernandezc** [comment]
Pytests do not pass (problem with configuration impacting matplotlib and this is due to changes in Traitlets)
I am working on it now.
