### ISSUE TITLE
spectrochempy API version 0.2.0 fails during import 

### ISSUE THREAD

**Issue by Luis-jacobo** [spectrochempy/spectrochempy#162]
**Describe the bug**
'scpy' not found in the style library and input is not a valid URL or path; see 'style.available' for list of available styles 

**To Reproduce**
1. Install spectrochempy as usual (follow installation guide for spectrochempy)
2. See error when execute  ' from spectrochempy import* '

**Expected behavior**
Loading SpectroChemPy API: 100%.

**Screenshots**
![CAPTURE2](https://user-images.githubusercontent.com/77514336/104784573-e1c6c100-5788-11eb-9c46-63a1f5b54c09.JPG)
![CAPTURE3](https://user-images.githubusercontent.com/77514336/104784590-ea1efc00-5788-11eb-813e-7859d7c1656e.JPG).

**Desktop (please complete the following information):**
 - Windows: [Windows 10]
 - Python version (3.8.5)
 - SpectroChemPy version [ 0.2.0]

**Additional context**

**Comment by fernandezc** [comment]
Thanks Luis for the report.

I think I found the line causing the problem. I temporarily removed the broken 0.2.0 version from Anaconda, and will build a new one tomorrow.

**Comment by fernandezc** [comment]
Dear Luis,
Could you please check the new version:
in your terminal environment:
```bash
mamba update -c spectrocat/label/dev spectrochempy
```
And tell me if it works for you. 
If not  you can always go back to the previous version using:
```bash
mamba update spectrochempy
```
If it work I will upload the new stable version.
There is some small change compare to the previous version: The corresponding docs are here:
```html
https://www.spectrochempy.fr/latest/index.html
```

**Comment by Luis-jacobo** [comment]
Dear Christian,

I will check the new version today and I'll tell you how it works to me. 




----- Mail d’origine -----
De: Christian Fernandez <notifications@github.com>
À: spectrochempy/spectrochempy <spectrochempy@noreply.github.com>
Cc: Luis-jacobo <luis-jacobo.aguilera@ensicaen.fr>, Author <author@noreply.github.com>
Envoyé: Sat, 16 Jan 2021 19:41:31 +0100 (CET)
Objet: Re: [spectrochempy/spectrochempy] 3.8.5 Py no compatibility with  spectrochempy 0.2.0 version (#162)

Dear Luis,
Could you please check the new version:
in your terminal environment:
```bash
mamba update -c spectrocat/label/dev spectrochempy
```
And tell me if it works for you. 
If not  you can always go back to the previous version using:
```bash
mamba update spectrochempy
```
If it work I will upload the new stable version.
There is some small change compare to the previous version: The corresponding docs are here:
```html
https://www.spectrochempy.fr/latest/index.html
```

**Comment by Luis-jacobo** [comment]
Dear Christian, 

Spectrochempy 0.1.22 works perfectly using mamba. All operations that I did before are operationals. 



De: "Christian Fernandez" <notifications@github.com> 
À: "spectrochempy/spectrochempy" <spectrochempy@noreply.github.com> 
Cc: "AGUILERA Luis-Jacobo" <luis-jacobo.aguilera@ensicaen.fr>, "Author" <author@noreply.github.com> 
Envoyé: Samedi 16 Janvier 2021 19:41:31 
Objet: Re: [spectrochempy/spectrochempy] 3.8.5 Py no compatibility with spectrochempy 0.2.0 version (#162) 





Dear Luis, 
Could you please check the new version: 
in your terminal environment: 
mamba update -c spectrocat/label/dev spectrochempy 


And tell me if it works for you. 
If not you can always go back to the previous version using: 
mamba update spectrochempy 


If it work I will upload the new stable version. 
There is some small change compare to the previous version: The corresponding docs are here: 
https://www.spectrochempy.fr/latest/index.html

**Comment by fernandezc** [comment]
Version 0.2.1 wil appears soon in the main anaconda repository.
