### ISSUE TITLE
Installation spectrochempy 0.2.1 does not complete

### ISSUE THREAD

**Issue by Luis-jacobo** [spectrochempy/spectrochempy#169]
**Describe the bug**
![image](https://user-images.githubusercontent.com/77514336/105039103-70289480-5a60-11eb-9557-bf15113494f1.png)

**To Reproduce**

1. conda install spectrochempy 
2. Verifying transaction : Failed

**Expected behavior**
Verifying transaction : Done

**Desktop:**
 - Windows: [10]
 - Python version (e.g;, 3.8.5)
 - SpectroChemPy version [e.g.,  0.2.1]

**Additional context**
The Raman test file has a character that does not recognize during the installation, after correct that the installation has been completed.

**Comment by fernandezc** [comment]
Thank you 
I will correct this.
