### ISSUE TITLE
Testing DSO and SRS needs some examples.

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#185]
To complete testing it is important to have some examples of the missing input for testing:

- Matlab DSO?
- Carrousel examples?  probably it is for now rather limited to LCS applications but testing is however needed.

Additionally some tutorials on how to use this would be welcome.

**Comment by fernandezc** [comment]
@atravert Just a recall, a lot of code has no tests! 
For this to be completed, I need file examples (at least one) to test read_srs and improve FFT transform of IR interferograms, as well as *.dso. 
For carrousel, I assume from the code that there is a file with metadata?  T
Would be great if you could provide this to me (send them using fileX for instance)!

**Comment by fernandezc** [comment]
OK now carrousel test and file examples are merged to the master branch. I leave it open as DSO and SRS need also some examples and test.

**Comment by atravert** [comment]
Solved by PR Feature/readers #209
