### ISSUE TITLE
Absorbance/transmittance

### ISSUE THREAD

**Issue by mw00847** [spectrochempy/spectrochempy#186]
**How should I switch between absorbance to transmittance for a .spa file **

**Desktop (please complete the following information):**

 - OS: Linux Ubuntu 
 - Python version 3.85
 - SpectroChemPy version 0.1.22

**Additional context**

**Comment by atravert** [comment]
For the moment this change of units is not implemented, but in the meantime the following works fine:

- if you want to convert and store the absorbance spectra (dataset `D_a`) in another dataset  `D_t` containing the transmittance spectra:

```
D_t = np.exp(-D_a/np.log10(np.e))   # change the absobance values to transmittance, equivalent to T = 10**-A
D_t.title = 'absorbance'  # changes the label of the data
D_t.ito('pct')   # optional if you want to have %transmittance 
```

- if you want to make the change inplace (i.e. in  `D_a`), then you can do the same but in the `data` field:

```
D_a.data = np.exp(-D_a.data/np.log10(np.e))   # change the absbance values to transmittance, equivalent to T = 10**-A
D_a.title = 'absorbance'  # changes the label of the data
D_a.ito('pct')   # optional if you want to have %transmittance 
```

**Comment by fernandezc** [comment]
> D_t.title = 'absorbance'  # changes the label of the data

this should be  read, I think 
```python
D_t.title = 'transmittance'  # changes the label of the data
```

**Comment by fernandezc** [comment]
I can add this transformation in the next version:
```python
D_t = D_a.to('transmittance')
```
should do the transformation transparently.

**Comment by atravert** [comment]
> 
> > D_t.title = 'absorbance'  # changes the label of the data
> 
> this should be read, I think
> 
> ```python
> D_t.title = 'transmittance'  # changes the label of the data
> ```
Yes, my mistake, sorry.

**Comment by fernandezc** [comment]
Now it is possible to do : 
```python3
    import spectrochempy as scp

    da = scp.read("irdata/nh4y-activation.spg")
    da -= da.min()
    da.plot()
    scp.show()

    dt = da.to('transmittance').    # conversion in % of transmittance
    dt.plot()
    scp.show()

    dt.ito('absolute_transmittance')
    dt.plot()
    scp.show()

    da = dt.to('absorbance')
    da.plot()
    scp.show()

    dt.ito('transmittance')
    dt.plot()
    scp.show()

    da = dt.to('absorbance')
    da.plot()
    scp.show()
```

This is accessible in version 0.2.5.dev1:    ` conda install -c spectrocat/label/dev spectrochempy`
