### ISSUE TITLE
Dealing with not implemented file format

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#207]
On my branch: `feature/readsrs` : Currently only certain series (.srs) files can be read ('rapid scan'), not 'GC IR' or 'TGA IR'. Currently this raises a `NotImplementedError` 

With this respect read() works as expected. But `scp.read('irdata', merge=True, recursive=True)` also raises the error if  'GC IR' or 'TGA IR' .srs file is present.

Do we want this ?, or should read() raise only a warning and return nothing for non readable .srs file ? or another solution ?

**Comment by fernandezc** [comment]
Right I thing we could just give a warning and ignore the unreadable files. Actually I already add something similar in my next commit, for file that can be present but we know that they cannot be read (.pdf, .docs, ...). In this case no warning but ignored. I will add this warning for the other unreadable files.

**Comment by atravert** [comment]
I had no problem to apply the patch. The warnings are now correctly raised but then    `scp.read('irdata', merge=True, recursive=True) ` seems to ignore all files whenever a non-readable file is present.

```
FAILED                                 [ 68%] WARNING | file C:\Users\traverta\Dropbox\Programmes\spectrochempy\scp_data\testdata\irdata\nh4.scp has a know extension but could not be read. It is ignored!
 WARNING | file C:\Users\traverta\Dropbox\Programmes\spectrochempy\scp_data\testdata\irdata\OPUS\background.0 has a know extension but could not be read. It is ignored!
 WARNING | file C:\Users\traverta\Dropbox\Programmes\spectrochempy\scp_data\testdata\irdata\subdir\TGAIR-unreadable.srs has a know extension but could not be read. It is ignored!
 WARNING | file C:\Users\traverta\Dropbox\Programmes\spectrochempy\scp_data\testdata\irdata\omnic series\TGA demo.srs has a know extension but could not be read. It is ignored!
 WARNING | file C:\Users\traverta\Dropbox\Programmes\spectrochempy\scp_data\testdata\irdata\omnic series\GC Demo.srs has a know extension but could not be read. It is ignored!
 WARNING | file C:\Users\traverta\Dropbox\Programmes\spectrochempy\scp_data\testdata\irdata has a know extension but could not be read. It is ignored!

tests\test_readers_writers\test_read_omnic.py:105 (test_read_spa)
0 != 5

Expected :5
Actual   :0
<Click to see difference>

def test_read_spa():
        nd = scp.read_spa('irdata/subdir/20-50/7_CZ0-100 Pd_21.SPA')
        assert str(nd) == 'NDDataset: [float32] a.u. (shape: (y:1, x:5549))'
    
        nd = scp.read_spa('irdata/subdir', merge=True)
        assert str(nd) == 'NDDataset: [float32] a.u. (shape: (y:4, x:5549))'
    
        nd = scp.read_spa('irdata/subdir', merge=True, recursive=True)
        assert str(nd) == 'NDDataset: [float32] a.u. (shape: (y:8, x:5549))'
    
        lst = scp.read('irdata', merge=True, recursive=True)  # not selective on extension
        assert isinstance(lst, list)
>       assert len(lst) == 5
E       assert 0 == 5

test_read_omnic.py:118: AssertionError

```

**Comment by atravert** [comment]
Also: `.0` extension is ignored (see above) while I think this opus file can be read.

**Comment by fernandezc** [comment]
Strange, I do not have the problem:
```ipython 
scp.read('irdata', merge=True, recursive=True)
```
return (on the console with py3.9)
```
 WARNING | file /Users/christian/Dropbox/SCP/spectrochempy/scp_data/testdata/irdata/subdir/TGAIR-unreadable.srs has a know extension but could not be read. It is ignored!
 WARNING | file /Users/christian/Dropbox/SCP/spectrochempy/scp_data/testdata/irdata/OPUS/background.0 has a know extension but could not be read. It is ignored!
Out[3]: 
[NDDataset: [float32] a.u. (shape: (y:1, x:11098)),
 NDDataset: [float32] unitless (shape: (y:1, x:3734)),
 NDDataset: [float32] a.u. (shape: (y:1, x:5549)),
...

```
only one .srs and the .0 opus file are not read. 

For the .0 file I have this problem since a long time already. Opus reader was not working on it.

**Comment by atravert** [comment]
OK.  I will check again and let you know :-)

**Comment by fernandezc** [comment]
One reason may be that you hadn't merged the upstream master yet? (version 0.2.6)

**Comment by atravert** [comment]
The problem was actually with 'readable' srs files ! : 

read_srs returned 2 datasets (the data, and the background which is not used for the moment), so apparently when a private _read_XXX() returns more than one dataset, read() applied to a directory  returns nothing, even if other files are readable.

As we don't use at all the 'background' for the moment I have changed  _read_srs()  so that it returns a single dataset and there is no need to change importer() with this repect. 

Now, by making the various trys: it appears that if a filename is mispelled, e.g. `rapid_scan_blabla.srs` instead of `rapid_scan.srs`, the following warning is returned:

`WARNING | file irdata\omnic series\rapid_scan_blabla.srs has a know extension but could not be read. It is ignored! `

This is related to issue #197:  importer() should return a specific error message when a filename (or a directory) specified in the funcntion call does not exist.

[I'll be in class the whole afternnon]

**Comment by atravert** [comment]
more explicitelyt 
importer()  hould return a specific error message when a filename (or a directory) specified in the funcntion call does not exist such as: WARNING | file irdata\omnic series\rapid_scan_blabla.srs does not exist. It is ignored!

**Comment by fernandezc** [comment]
OK, I will check this soon, but I have a worry that you have not merged the upstream master branch. Without this we have a chance to have different behaviors, because we do not check the same code!

You need to pull the upstream into your master branch, and after this rebase your working branches on master.

**Comment by fernandezc** [comment]
Ok I just had a look to this issue. I will change the behavior this way:
- if a file does not exist it will tell us.
- if a file cannot be read it will specify this.
That's I think what we would expect.

**Comment by fernandezc** [comment]
Ok I have changed the error message. This could be improved. 

See the following patch:
[patch.diff.zip](https://github.com/spectrochempy/spectrochempy/files/5928297/patch.diff.zip)

![image](https://user-images.githubusercontent.com/2428474/106950656-03cfb580-672f-11eb-928f-d77b4a2bf053.png)

**Comment by atravert** [comment]
That's perfect !  (once dso/srs examples done, I will look at the opus 
backround issueà


Le 04/02/2021 à 21:25, Christian Fernandez a écrit :

**Comment by fernandezc** [comment]
well, in this case I close this issue. May be you can open one for the reap_opus issue, if you like.
