### ISSUE TITLE
 `write_csv()`: dialog box 

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#222]
**Describe you problem**

 In banch atravert:`feature/write_csv`  I have written `write_csv()` routine for 1D datasets which work fine except that it opens a dialog box even when the filename is passed as argument. According to the doc,  `exporter()` should write it in the currend dir. Did I miss something ?

**Comment by fernandezc** [comment]
use confirm = False

https://www.spectrochempy.fr/stable/userguide/importexport/importIR.html#Import/Export-of-JCAMP-DX-files

**Comment by atravert** [comment]
Thanks ! Then shouldn't we set `confirm` to `False` by default ? (if a user enters a filename, he probably knows what he is doing ?

**Comment by fernandezc** [comment]
Sure, but this can be discussed. I think this more dangerous to write than to read, right? ... or we need to put additional checking to avoid overriding some existing files. I would prefer to put a dialog by default.

**Comment by atravert** [comment]
Yes of course. So we let it as it is fore the moment :-).
