### ISSUE TITLE
baseline correction on non-default dimension 

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#227]
**Describe the bug**
An error is raised when a baseline correction is made on the dimension `0` (`y`)of a 2D dataset

**To Reproduce**
```
import spectrochempy as scp

# IR spectrum, we want to make a baseline correction on the absorbance vs. time axis:
ir = scp.read('irdata/nh4y-activation.spg')
ir.y = ir.y - ir[0].y
blc = scp.BaselineCorrection(ir[:,2000.0:2020.0], dim=0)
blc.compute(*[[0., 2.e3], [3.0e4, 3.3e4]], interpolation='polynomial', order=1, method='sequential')
blc.corrected.plot()
plt.show()

# MS profiles, we want to make a baseline correction on the ion current vs. time axis:
ms = scp.read('msdata/ion_currents.asc', timestamp=False)
blc = scp.BaselineCorrection(ms[10.:20.,:], dim=0)
blc.compute(*[[10., 11.], [19., 20.]], interpolation='polynomial', order=1, method='sequential')
blc.corrected.T.plot()
plt.show()
```

**Expected behavior**

**Comment by fernandezc** [comment]
Arnaud,
I think the best is to use the technique I used with processing function: alway Transpose or swap dims in order to have the working dimension on the last axis. It is less complicated and also faster to work on the last dimension with Numpy functions.

**Comment by fernandezc** [comment]
```python
            # On which axis do we want to apodize? (get axis from arguments)
            axis, dim = dataset.get_axis(**kwargs, negative_axis=True)

            # output dataset inplace (by default) or not
            if not kwargs.pop('inplace', False) and not dryrun:
                new = dataset.copy()  # copy to be sure not to modify this dataset
            else:
                new = dataset

            # The last dimension is always the dimension on which we apply the apodization window.
            # If needed, we swap the dimensions to be sure to be in this situation
            swaped = False
            if axis != -1:
                new.swapdims(axis, -1, inplace=True)  # must be done in  place
                swaped = True
....(do staff)
            # restore original data order if it was swaped
            if swaped:
                new.swapdims(axis, -1, inplace=True)  # must 
```

**Comment by atravert** [comment]
Yes I tried this solution but still got an error (well it was late 
yesterday, so I was probably confused : I will try again and let you know !

Le 11/02/2021 à 10:25, Christian Fernandez a écrit :

**Comment by atravert** [comment]
Same error with the transpose:
```
# IR spectrum, we want to make a baseline correction on the absorbance vs. time axis:
ir.y = ir.y - ir[0].y
ir_t = ir.T
blc = scp.BaselineCorrection(ir_t[2000.0:2020.0,:])
blc.compute(*[[0., 2.e3], [3.0e4, 3.3e4]], interpolation='polynomial', order=1, method='sequential')
blc.corrected.T.plot()
plt.show()
```

**Comment by atravert** [comment]
and swapdims:

```
# IR spectrum, we want to make a baseline correction on the absorbance vs. time axis:
ir.y = ir.y - ir[0].y
ir_s = ir.swapdims(0,1)
blc = scp.BaselineCorrection(ir_s[2000.0:2020.0,:])
blc.compute(*[[0., 2.e3], [3.0e4, 3.3e4]], interpolation='polynomial', order=1, method='sequential')
blc.corrected.T.plot()
plt.show()
```

**Comment by fernandezc** [comment]
```python
....
blc.corrected.plot()
plt.show()
...
```
Not related, but I take the occasion to talk about this: I see you use pyplot here.... `plt.show` ... you can use `scp.show` in the examples instead. I have the feeling that it make the things clearer  for the beginners. as you don't need to import pyplot.  BUT of course this is not mandatory :).

**Comment by atravert** [comment]
👍   I wasn't aware of this possibilite. Indeed it is much more clear     (NB: pyplot is also imported automatically as plt with spectrochempy  )

**Comment by fernandezc** [comment]
If you use `import spectrochempy as scp` I don't think pyplot is available without doing another import.... same for Numpy.
OF course it is already imported as Numpy if you do `from spectrochempy import *`

**Comment by atravert** [comment]
yes, my mistake.

**Comment by fernandezc** [comment]
Are you working on this issue with bc and transpose or do you want me to have a look?

**Comment by fernandezc** [comment]
@atravert I think I have fixed the issue, it will appear in the next PR merge. I also included your changes in the branch feature/multcoord.  Be careful, that for baseline correction, the options must be passed in compute (not anymore at the initialisation of BaselineCorrection instance). This was a source of confusion and mostly wrong. (A message will inform the user, in case it is still called the old way).  

```python
blc = scp.BaselineCorrection(X)
blc.compute(*ranges, interpolation='pchip', method='multivariate', npc=2)
```
or
```python
blc(*ranges, interpolation='pchip', method='multivariate', npc=2)  # equivalent to blc.compute(...)
```

**Comment by atravert** [comment]
OK, but the fix in feature/multcoord was not functional yet.

regardingthe BaselineCorrection class it is clear now. Still, from the 
user perspective would it be possible to add a dataset method that would 
allow baseline correction in a single command line ? , e.g. something like:

Xcorr = scp.BaselineCorrect(X,*ranges, interpolation='pchip', 
method='multivariate', npc=2)

or

Xcorr = X.BaselineCorrect(*ranges, interpolation='pchip', 
method='multivariate', npc=2)

where Xcorr is the baslinecorrected dataset ?


le 25/02/2021 à 19:19, Christian Fernandez a écrit :

**Comment by fernandezc** [comment]
> OK, but the fix in feature/multcoord was not functional yet.

I didn't test it indeed. I leave you continue your work but you can start from the current fonction ;-) 

> Xcorr = scp.BaselineCorrect(X,*ranges, interpolation='pchip', method='multivariate', npc=2)

Well I think the best would be to create a new function. I suggest `basc' : 

```python
def basc(dataset, *ranges, **kwargs):
      return BaselineCorrection(dataset).compute(*ranges, **kwargs)
```
but I prefer not to modify BaselineCorrection. Indeed, we could do everything in one line, but in this case we will loose the other functions of this class: i.e., run for interactive, show_regions to display ranges, ... and the future that could be added. 

If you agree I will add the `basc` function in the next PR.

**Comment by atravert** [comment]
Absolutely:  BaselineCorrect is very usefull for advanced usages/users 
and can be easily developed to return useful data such as the polynomial 
coefs, goodness-of-fit in the *ranges regions, etc...

'basc' is perfect: short and meaningful :-)

Le 26/02/2021 à 01:24, Christian Fernandez a écrit :
