### ISSUE TITLE
LinearCoord still not working properly

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#243]
LinearCoord do not concatenate correctly. This leads to e.g. awkward baselinecorrections (this is how i found the bug)

**To Reproduce**

```
D = scp.NDDataset.zeros((10,100))

x = scp.LinearCoord(offset=0.0, increment=1.0, size=100)
y = scp.LinearCoord(offset=0.0, increment=1.0, size=10)

D.set_coordset(x=x, y=y)
D1 = D[:,0.:10.]
D2 = D[:,20.:40.]

D12 = scp.concatenate(D1, D2, axis=1)

# D2.x.data[-1] is 40., as expected, but not D12.x.data[-1]:
D12.x.data[-1] == D2.x.data[-1]

```

**Expected behavior**
in the example above, the `D12` `x` axis values are 0, .... 31, but should be 0, ..., 10, 20, ....40

**Comment by fernandezc** [comment]
Yep ... looks like something is missing: in this case the new coordinate is no more linear, so a transformation needs to be applied internally.

**Comment by fernandezc** [comment]
Actually, there is more than this error with LinearCoord - indexation for instance doesn't work always well. I am gonna work on this. But the present issue is corrected in the next pull request.

**Comment by atravert** [comment]
OK. Then in the meantime, I propose to switch back to classic Coords in 
read_spa() until LinearCooord has been fully tested ?


Le 18/02/2021 à 09:38, Christian Fernandez a écrit :

**Comment by fernandezc** [comment]
Yes it's possibility, but I am on the problem. 
As a workaround if you have this kind of problem, after the merge you will be able to do:

```dataset.x = scp.Coord(dataset.x, linear=False)```

to transform LinearCoord to Coord.

**Comment by atravert** [comment]
OK fine :-)  On my side I will also check the LinearCoord.data values 
against former method and omnic : I have noticed a slight difference in 
one casz but I need to double check


Le 18/02/2021 à 09:57, Christian Fernandez a écrit :

**Comment by fernandezc** [comment]
Still some problem with LinearCoord : see issues #246 #247

**Comment by fernandezc** [comment]
Regarding baseline correction, the issue is just for documentation. 
There is still a problem with align in several dimensions but I will open a new issue for this specific problem.
