### ISSUE TITLE
Apodization function 

### ISSUE THREAD

**Issue by Bio-data-tricks** [spectrochempy/spectrochempy#274]
Hi everyone, 

I would like to perform a water interference correction on FTIR spectra. I have water theoretical spectra obtain via Hitran, but I'm not sure what apodization function I need to use on these theoretical spectra to make them look like my experimental spectra.  Have you an idea ? Is it possible to do that with spectrochempy ? 

Thank you ! 

Nicolas

**Comment by atravert** [comment]
Nicolas,

spectrochempy has a number of methods to process spectra or interferograms (see here: https://www.spectrochempy.fr/latest/userguide/processing/processing.html).

Regarding the correction of water interferences:  the usual way to do it is is to use an experimental spectrum of water recorded in the same (or similar) conditions than those used for the spectra to be corrected and then make a subtraction. With this respect, spectrichempy has the autosub function which sets the subtractiopn coefficients so as to minimize, e.g., water interferences (https://www.spectrochempy.fr/latest/userguide/reference/generated/spectrochempy.autosub.html?highlight=autosub#spectrochempy.autosub ).

I hope this helps.
Arnaud

**Comment by atravert** [comment]
close the issus (no reply after 2 weeks)
