### ISSUE TITLE
Reference on awesome-spectra?

### ISSUE THREAD

**Issue by erwanp** [spectrochempy/spectrochempy#275]
Hello ! Just discovered this package; great to see more open-source tools for spectroscopy !

I try to maintain a list of relevant spectroscopic packages here : https://github.com/erwanp/awesome-spectra 

You would be interested in adding spectrochempy and other packages you may know how is the section that looks the more relevant to you (or create a new one if needed) ? 

Best

**Comment by atravert** [comment]
Hello Erwan,

Thank you for your interest. As a general purpose tool, spectrochempy could be added in the following sections:
- Infrared
- Raman
- UV/Vis
- Post-processing

We also use it for NMR spectroscopy

so all in all, a 'General purpose' section would be great :-)

Best regards
arnaud

**Comment by erwanp** [comment]
Nice ! I can add it myself unless you want to submit a PR there !

**Comment by atravert** [comment]
PR including reference to spectrochempy has been made : https://github.com/erwanp/awesome-spectra/pull/7
