### ISSUE TITLE
Getting ImportError when trying to use basic stuff

### ISSUE THREAD

**Issue by Veenk** [spectrochempy/spectrochempy#334]
I installed everything needed with pip, to determine what was missing I just run the import statement. When everything was successfully installed and ready, I ones again run basic import script, and got ImportError like this one:

```
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\scientificProject', 'C:/scientificProject'])
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.30.1
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
In[2]: runfile('C:/scientificProject/main.py', wdir='C:/scientificProject')
Loading SpectroChemPy API:   8%|▊         | 92/1211 [00:00<00:06, 166.52it/s][SpectroChemPy] ERROR | ImportError: spectrochempy.core.dataset.ndarray
Loading SpectroChemPy API:   8%|▊         | 92/1211 [00:20<00:06, 166.52it/s]
```
What could go wrong? Maybe I need specific versions of preinstalled packages?

 - OS: Windows 10
 - Python version: 3.8.5 x64
 - SpectroChemPy version: 0.1.22

**Comment by fernandezc** [comment]
Hi,
Currently SpectroChemPy is developed using Conda. 
It has not tested with Pip installation. 
I may have a look to this problem, in the next days, but if you have a mean to do the installation using Conda, I advise this solution as indicated in the Doc  it will work for sure (although it is probably not yet bug free :)) 
Best regards and thank you for the interest.

**Comment by Veenk** [comment]
Thank you for a quick reply! I will go with Conda then :)

**Comment by fernandezc** [comment]
I have tried to install it using pip. 

pip install --upgrade pip
pip install -r requirements.txt 
cd <spectrochempy source dir> 
pip install -e .

For me it work using this content for the  requirements.txt  file : 

quadprog==0.1.9
brukeropusreader
numpy-quaternion
nmrglue
colorama
dill
ipython
jinja2
mamba
matplotlib
numba
numpy>=1.21.0
orderedset
pint==0.16.1
plotly
requests
scipy
tqdm
traitlets
traittypes
xlrd
setuptools
setuptools_scm
gitpython
ipywidgets
ipympl
jupyterlab>=2.2.10
nodejs
pytest
pytest-doctestplus
pytest-flake8
scikit-image
coverage
black
pre-commit
jupytext
sphinx==4.2.0
sphinx_rtd_theme
autodocsumm
sphinx-gallery<=0.7.0
nbsphinx
jupyter_sphinx
json5
sphinx-copybutton
autodoc_traits


Some of the package are however not needed if you don't work with the development of spectrochempy.  

Also the example are missing as it is a conda only package:  spectrochempy_data.

Later, I will try to publish a Pypi package to simplify this installation with pip.

**Comment by fernandezc** [comment]
**Update**

the pypi package has now been updated and is working. 

So installation using pip is as simple as (on windows):

```Powershell
# create an isolated environment:
python -m venv env
 .\env\Scripts\activate

# install dependencies
python -m pip install -r https://www.spectrochempy.fr/downloads/requirements.txt 

# install spectrpchempy
python -m pip install spectrochempy
```

on Mac/linux replace the env activation line by : 
```bash
source env/bin/activate
```
