### ISSUE TITLE
exceptions and warnings in readers

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#349]
**Describe the bug**
Exceptions and warnings raised in private reader fucntions (e.g. _read_spa) are not printed out, even in DEBUG mode. In case of exception, the only message that is issued is 'XXXX has a known extension but it could not be read. It is ignored!, which complicates the debugging 

**To Reproduce**
- launch test_read_omnic/test_read_srs() in debug mode with a stop in line 905 of readomnic.py

read_srs detects that the file is not of rapidscan type and issues a NotImplementedError wchich is finally ignored 

**Expected behavior**
If a n error or warning is raised purposedly in the readers, it should be printed out so that the user knows why his file cannt be read.

**Comment by fernandezc** [comment]
OK. I will go back into this - I recently made some change that could explain the behaviour. The thing is to determine which errors are blocking (giving an exception) and those which can be accepted for example when we do a read of a complete directory (I agree that message should be issued).

**Comment by fernandezc** [comment]
(with the LAST version of master in the main repository) I get this 

```python
import spectrochempy as scp
scp.read("irdata/omnic series/GC Demo.srs")
 ```
returns:
```
WARNING | Only implemented for rapidscan
````
Is this what you expect?

**Comment by fernandezc** [comment]
Actually if you update to this version you should see many change that (I hope) solve these problems. 
Note that testing of the main readers functionalities has been made in the test_importer.py,  and that readers such as read_omnic should test only specifics to this protocol. Of course something may be still missing.

**Comment by fernandezc** [comment]
I am closing this now, but feel free to reopen it if you need.

**Comment by atravert** [comment]
Yes !  This is fine, I will update my version. Thanks !

Le 16/01/2022 à 20:25, Christian Fernandez a écrit :
