### ISSUE TITLE
[Bug]: plot_bar() and twinx not working in PCA.screeplot()

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#375]
### What happened?

See the [PCA example](https://www.spectrochempy.fr/stable/gettingstarted/gallery/auto_examples/analysis/plot_pca_iris.html#sphx-glr-gettingstarted-gallery-auto-examples-analysis-plot-pca-iris-py). Screeplot should display a single figure with a bar plot (explained variance) with blue y axis on the left  + a scatter plot with lines (cumulated variance), with y axis in red on the right.  
- The bar plot is not displayed anymore - this is due to the fact that in `plot1D` line 146  `scatter` is set to `"default"` , the default value of `marker` . As scatter is not None, `line` is set to an ax.plot(...) (line 434+) , and not to ax.bar (line 450+) as it should be.  note that the bar plot is obtained if line 446:
```scatter = "scatter" in method  or marker```
is replaced by:
```scatter = "scatter" in method``` 
 but I don't know why `or marker` was put in the first place :-)

- The second error is related to `twinx` which seems not working anymore: despite `twinx=ax1` is passed, `ax2` is plot in a separate figure. I have tried few workarounds but did not get satiofactory result... 

### What did you expect to happen?

The screeplot as it was before :-)

### Environment

INSTALLED VERSIONS
------------------
commit: 53b50aaf9e0a9619a03f17cfa7ab7b6c7dae1479
python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'ISO8859-1')
conda-forge: None
spectrocat: None
defaults: None
quadprog: 0.1.11
brukeropusreader: 1.3
quaternion: 2020.5.19.15.27.24
nmrglue: 0.9-dev
colorama: 0.4.4
dill: 0.3.4
ipython: None
jinja2: 2.11.2
matplotlib: 3.5.1
numba: 0.50.1
numpy: 1.21.2
orderedset: 2.0.3
pint: 0.16.1
plotly: 4.14.3
requests: 2.24.0
scipy: 1.7.1
tqdm: 4.51.0
traitlets: 5.0.5
traittypes: 0.2.1
xlrd: 1.2.0
spectrochempy_data: None
setuptools: 57.4.0
setuptools_scm: 4.1.2
git: 3.1.26
ipywidgets: 7.5.1
ipympl: 0.5.8
jupyterlab: 3.1.7
nodejs: 0.1.1
spectrochempy: 0.2.16.dev29

**Comment by fernandezc** [comment]
Ummmh... looks like my previous refactoring is not completely satisfactory 🙂 ... 

And the test notably insufficient... I'll come back to it soon.

**Comment by fernandezc** [comment]
Well, there is one more thing that doesn't work well at least for the documentation... it's that the place for the second ax2 axis remains reserved, so it's a big blank. I'll look into it, but we really need to improve the pad tests. We can't just look at the final result because it's too much time spent unnecessarily
