### ISSUE TITLE
Add better tests for plotting and get few issues solved

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#379]
Few issues with plotting remains to be solved, like the one reported in the comment below. Better test will help to avoid new problem like this appear again. 

----
Well, there is one more thing that doesn't work well at least for the documentation... it's that the place for the second ax2 axis remains reserved, so it's a big blank. I'll look into it, but we really need to improve the plot tests. We can't just look at the final result because it's too much time spent unnecessarily

_Originally posted by @fernandezc in https://github.com/spectrochempy/spectrochempy/issues/375#issuecomment-1025560018_

**Comment by atravert** [comment]
Yes, I saw it. But it is not systematic: in the user guide, [here](https://www.spectrochempy.fr/latest/userguide/analysis/mcr_als.html#Initial-guess-and-MCR-ALS-optimization), it works fine...
I agree on tests. Now I will add them systematically when working on an analysis method (currently i am adding tests on PCA to improve coverage, and after this I will go on MCRALS).
