### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'quaternion'

### ISSUE THREAD

**Issue by petsuter** [spectrochempy/spectrochempy#402]
### What happened?

```
>>> import spectrochempy as scp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spectrochempy\__init__.py", line 59, in <module>
    from spectrochempy import api
  File "spectrochempy\api.py", line 88, in <module>
    from . import core
  File "spectrochempy\core\__init__.py", line 31, in <module>
    from ..utils import pstr  # noqa: E402
  File "spectrochempy\utils\__init__.py", line 28, in <module>
    from .print import *
  File "spectrochempy\utils\print.py", line 6, in <module>
    from .misc import TYPE_INTEGER, TYPE_COMPLEX, TYPE_FLOAT
  File "spectrochempy\utils\misc.py", line 19, in <module>
    from quaternion import as_float_array, as_quat_array
ModuleNotFoundError: No module named 'quaternion'
```

### What did you expect to happen?

No error when importing spectrochempy.

### Environment

I can't import scp.

**Comment by petsuter** [comment]
I tried `pip install quaternion` but apparently that is the wrong library.
 `pip install numpy-quaternion` would be the right one apparently.

(But `pip uninstall quaternion` *has* to be ran first. Otherwise (on Windows) both libraries use the `Quaternion` package name (with uppercase Q!) so nothing works. This is a bit unrelated to spectrochempy I guess, I just wanted to let you know anyway.)

But apparently I should have followed this: https://www.spectrochempy.fr/stable/gettingstarted/install/install_win.html#installation-using-pip

**Comment by fernandezc** [comment]
Similar  issues as #401
