### ISSUE TITLE
NDDataset corruption with write/read scp

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#417]
### What happened?

Writing and reading a NDDataset in scp format leads to strange behaviour when making simple operations such as subtraction:

for instance, `x_r = X - X[-1]` does not give the proper result.  But using the data field for the second operand works (`x_r2 = X - X[-1].data`) 

```
import spectrochempy as scp
import numpy as np

X = scp.read_omnic("irdata/nh4y-activation.spg")
x = X - X[-1]

print("--subtract with ds from read_omnic")
print(f"mean x: {np.mean(x.data)}")
print(f"var x: {np.var(x.data)}")
print("")

X.write("X.scp")
X_r = scp.read("X.scp")
x_r = X_r - X_r[-1]

print("--subtract after write/read_scp")
print(f"mean x_r: {np.mean(x_r.data)}")
print(f"var x_r: {np.var(x_r.data)}")
print("")

x_r2 = X_r - X_r[-1].data
print("--subtract with data field")
print(f"mean x_r2: {np.mean(x_r2.data)}")
print(f"var x_r2: {np.var(x_r2.data)}")
```

Here is the output:

```
SpectroChemPy's API - v.0.4.2.dev11+g14b728d69
© Copyright 2014-2022 - A.Travert & C.Fernandez @ LCS
--subtract with ds from read_omnic
mean x: 0.16722696114198038
var x: 0.23486294966826882
--subtract after write/read_scp
mean x_r: 1.104111572321127
var x_r: 1.4657190686887622
--subtract with data field
mean x_r2: 0.16722696114198038
var x_r2: 0.23486294966826882
```

### What did you expect to happen?

x and x_r above should be identical.

### Minimal Complete Verifiable Example

```python
import spectrochempy as scp
import numpy as np

X = scp.read_omnic("irdata/nh4y-activation.spg")
x = X - X[-1]

print("--subtract with ds from read_omnic")
print(f"mean x: {np.mean(x.data)}")
print(f"var x: {np.var(x.data)}")
print("")

X.write("X.scp")
X_r = scp.read("X.scp")
x_r = X_r - X_r[-1]

print("--subtract after write/read_scp")
print(f"mean x_r: {np.mean(x_r.data)}")
print(f"var x_r: {np.var(x_r.data)}")
print("")

x_r2 = X_r - X_r[-1].data
print("--subtract with data field")
print(f"mean x_r2: {np.mean(x_r2.data)}")
print(f"var x_r2: {np.var(x_r2.data)}")
```

### Environment

Note: scp.show_versions() does not sho the correct version of scpy, maybe because it is a git clone in my case ?

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:22:07) [MSC v.1929 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'ISO8859-1')
quadprog: None
brukeropusreader: 1.3
quaternion: 2021.11.4.15.26.3
colorama: 0.4.4
dill: 0.3.4
ipython: None
jinja2: 3.0.3
matplotlib: 3.5.1
numba: 0.55.0
numpy: 1.21.5
orderedset: 2.0.3
pint: 0.18
plotly: 4.14.3
requests: 2.24.0
scipy: 1.7.1
tqdm: 4.51.0
traitlets: 5.0.5
traittypes: 0.2.1
xlrd: 1.2.0
spectrochempy_data: None
setuptools: 60.9.3
setuptools_scm: 4.1.2
git: 3.1.26
ipywidgets: 7.6.5
ipympl: 0.8.8
jupyterlab: 3.3.0
nodejs: 0.1.1
pip: 21.3.1
spectrochempy: 0.2.16.dev29

**Comment by fernandezc** [comment]
Ok.  I will look at this ASAP

**Comment by fernandezc** [comment]
It's my fault! I didn't notice that the comparison of two dimensionless units is not obvious: 

```python
ur.absorbance == ur.transmittance   # wrongly True
f"{ur.absorbance:~P}" = f"{ur.absorbance:~P}"   # False as expected!
```
