### ISSUE TITLE
[Bug]: KeyError: 136 on OPUS file read in

### ISSUE THREAD

**Issue by ManusGit9** [spectrochempy/spectrochempy#479]
### What happened?

I am currently trying too read in OPUS files ([...].0, [...].1, ...formats) from my FTIR experiments using the NDDataset.read(>filepath<) function. For some OPUS files it works just fine (including plotting), however for others i get a "KeyError: 136" with the traceback shown below (I replaced the irrelevant folder names with their purpose in >...<). I am currently using spectrochempy version from 0.4.7.

The file "OPUS_files_plotting_test_extended.ipy" Is the one plotting the OPUS dataset (using .ipy, and functions recommended like on the spectrochempy).

I attached the data file as a .zip below.
[FTIR_measurement_OPUS_format.zip](https://github.com/spectrochempy/spectrochempy/files/9527710/FTIR_measurement_OPUS_format.zip)

### What did you expect to happen?

I expected to get a plot of the input file spectrum in the plot window of Spyder.

### Minimal Complete Verifiable Example

```python
%matplotlib inline
import spectrochempy as scp

data_path = >data file path<

dataset = scp.NDDataset.read( data_path )

dataset = dataset[:, 4000.0:650.0] 

dataset.y -= dataset.y[0]
dataset.y.ito("minutes")
dataset.y.title = "relative time on stream"

_ = dataset.plot()
```

### Relevant log output

```python
Traceback (most recent call last):

  File "/home/>user</>spectrochempy_install_folder</anaconda3/envs/scpy/lib/python3.10/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/>user</>script_folder</OPUS_files_plotting_test_extended.ipy", line 35, in <module>
    dataset = scp.NDDataset.read( data_path )

  File "/home/>user</>spectrochempy_install_folder</anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/readers/importer.py", line 446, in read
    return importer(*paths, **kwargs)

  File "/home/>user</>spectrochempy_install_folder</anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/readers/importer.py", line 132, in __call__
    self._switch_protocol(key, self.files, **kwargs)

  File "/home/>user</>spectrochempy_install_folder</anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/readers/importer.py", line 205, in _switch_protocol
    res = read_(self.objtype(), filename, **kwargs)

  File "/home/>user</>spectrochempy_install_folder</anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/readers/read_opus.py", line 180, in _read_opus
    opus_data = _read_data(fid)

  File "/home/>user</>spectrochempy_install_folder</anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/readers/read_opus.py", line 238, in _read_data
    opus_data = parse_data(data, meta_data)

  File "/home/>user</>spectrochempy_install_folder</anaconda3/envs/scpy/lib/python3.10/site-packages/brukeropusreader/opus_parser.py", line 60, in parse_data
    name, parser = block_meta.get_name_and_parser()

  File "/home/>user</>spectrochempy_install_folder</anaconda3/envs/scpy/lib/python3.10/site-packages/brukeropusreader/block_data.py", line 67, in get_name_and_parser
    return BLOCK_7[self.channel_type], parse_series

KeyError: 136
```

### Anything else we need to know?

I renamed the data file before packaging it, to test if the filename was too long, but as far as i know, this is not the problem here, since the same error occurred after renaming it. If this is a problem, I can also upload the file with the original name.

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
python-bits: 64
OS: Linux
OS-release: 5.15.0-46-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: ('en_US', 'UTF-8')

quadprog: 0.1.11
brukeropusreader: 1.3
quaternion: 2022.4.1
cantera: None
colorama: 0.4.5
dill: 0.3.5.1
ipython: None
jinja2: 3.0.3
matplotlib: 3.5.2
numba: 0.55.0
numpy: 1.21.5
pint: 0.19.2
requests: 2.28.1
scipy: 1.7.3
tqdm: 4.64.1
traitlets: 5.1.1
traittypes: 0.2.1
xlrd: 2.0.1
pyyaml: None
ipywidgets: 8.0.2
ipympl: 0.9.2
setuptools: 65.3.0
setuptools_scm: 7.0.5
git: None
jupyterlab: 3.4.5
nodejs: None
pytest: None
pytest-doctestplus: None
pytest-flake8: None
pytest-mock: None
pyfakefs: None
scikit-image: None
coverage: None
black: 22.6.0
pre-commit: None
cffconvert: None
mamba: 0.25.0
jupytext: None
sphinx: 5.1.1
sphinx_rtd_theme: None
autodocsumm: None
sphinx-gallery: None
nbsphinx: None
jupyter_sphinx: None
json5: 0.9.5
sphinx-copybutton: None
numpydoc: 1.4.0
pandoc: None
conda-build: None
conda-verify: None
anaconda-client: None
xarray: None
scikit-learn: None
dash: None
dash-bootstrap-components: None
dash: None
daq: None
jupyter-dash: None
plotly: None
pip: 22.2.2
autodoc_traits: None
dash_defer_js_import: None
dash-ace: None
spectrochempy: 0.4.7

**Comment by atravert** [comment]
Thank you for your message. I will look at this bug asap.
Best regards
Arnaud

**Comment by atravert** [comment]
Hello,

The error was related to the brukeropusreader package. The data file that couldn't be read contains two spectra - probably a 'raw' spectrum and 'post-treated' (?) spectrum. The error was related to the reading of additional informations related to the 'raw' spectrum (single channel spectra, interferograms, and acquisition parameters of the sample and reference). This is fixed now and you can update this package in your conda environement using: 

`conda update -c spectrocat brukeropusreader`

Please note that spectrochempy will only import the 'post-treated' spectrum  in the dataset. But you can access the other data by the direct use of brukeropusreader, as explained here: https://www.spectrochempy.fr/latest/userguide/importexport/importIR.html#Import-of-Bruker-OPUS-files

The code below shows how to plot the 'raw' and 'post-treated' spectra, and theii differences: 
```
from brukeropusreader import read_file
import matplotlib.pyplot as plt

data = read_file("2022-08-29_at600mV_2.0")

plt.plot(data['AB'])               # data['AB'] is the "post-treated" absorbance spectrum  
plt.plot(data['AB_(1)'])          # data['AB_(1)'] is the "raw" absorbance spectrum 
plt.plot(10*(data['AB'] - data['AB_(1)']))
plt.show()
```
Please let me know if this fix is working for you. Also let us know if you would like directly import the "raw" spectrum in spectrochempy. We can add optional parameter(s) in the reader to to that.

Best regards
Arnaud
