### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'pint.unit' in Linux environment

### ISSUE THREAD

**Issue by PereraUmesha** [spectrochempy/spectrochempy#490]
### What happened?

When I import spectrochempy, I get the following ModuleNotFoundError. This happend in WSL (Debian) environment and when I do a "pip install pint", I get "Requirement is already satified"

  File "/home/umesha/RC/UEC_FT-IR_UE012_2/code/src/spa2img.py", line 18, in <module>
         import spectrochempy as scp                                                                                                                            
  File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/__init__.py", line 59, in <module>
         from spectrochempy import api 
  File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/api.py", line 89, in <module>
         from . import core
   File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/core/__init__.py", line 31, in <module> 
        from ..utils import pstr  # noqa: E402
   File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/utils/__init__.py", line 30, in <module>
        from .jsonutils import *  
   File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/utils/jsonutils.py", line 20, in <module> 
       from spectrochempy.core.units import Quantity, Unit
   File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/core/units/__init__.py", line 12, in <module>
      from .units import *  # noqa: F403, F401, E402
   File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/core/units/units.py", line 32, in <module>
     from pint.unit import UnitsContainer, Unit, UnitDefinition
ModuleNotFoundError: No module named 'pint.unit'                                             

### What did you expect to happen?

I expected to run without the above error

### Environment

In this vertual environment (Python 3.9.12 ), I have installed only matplotlib and spectrochempy using pip
asttokens==2.0.8
backcall==0.2.0
brukeropusreader==1.3.4 
certifi==2022.9.24
charset-normalizer==2.1.1
colorama==0.4.6
contourpy==1.0.5
cycler==0.11.0
debugpy==1.6.3
decorator==5.1.1
dill==0.3.6
entrypoints==0.4 
executing==1.1.1
fonttools==4.38.0
gitdb==4.0.9
GitPython==3.1.29
idna==3.4
ipykernel==6.16.2
ipympl==0.9.2
ipython==8.5.0
ipython-genutils==0.2.0
ipywidgets==8.0.2
jedi==0.18.1
Jinja2==3.0.3
jupyter_client==7.4.4
jupyter_core==4.11.2
jupyterlab-widgets==3.0.3
kiwisolver==1.4.4
llvmlite==0.38.1
MarkupSafe==2.1.1
matplotlib==3.6.1
matplotlib-inline==0.1.6
nest-asyncio==1.5.6
numba==0.55.0
numpy==1.21.5
numpy-quaternion==2022.4.2
packaging==21.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
Pint==0.20
prompt-toolkit==3.0.31
psutil==5.9.3
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.13.0
pyparsing==3.0.9
python-dateutil==2.8.2
PyYAML==6.0
pyzmq==24.0.1
quadprog==0.1.11
requests==2.28.1
scipy==1.7.3
setuptools-scm==7.0.5
six==1.16.0
smmap==5.0.0
spectrochempy==0.4.7
stack-data==0.5.1
tomli==2.0.1
tornado==6.2
tqdm==4.64.1
traitlets==5.1.1
traittypes==0.2.1
typing_extensions==4.4.0
urllib3==1.26.12
wcwidth==0.2.5
widgetsnbextension==4.0.3
xlrd==2.0.1

**Comment by fernandezc** [comment]
Hello,

This is probably due to a very recent change in pint (0.19.2 --> 0.20 from yesterday). Could you try to Install to the previous version of pint:   pip uninstall pint / pip install pint=0.19.2. ?

If this work, we will take care of this problem ASAP to make the necessary upgrade.
christian

**Comment by PereraUmesha** [comment]
Hello,
Thank you so much. Installing pint=0.19.2 made that error dissapear.

However, now I'm getting another error on tkinter as below:
----------------------------------------------
    import spectrochempy as scp
  File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/__init__.py", line 59, in <module>
   from spectrochempy import api
  File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/api.py", line 89, in <module>
   from . import core
  File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/core/__init__.py", line 366, in <module>
    from tkinter import filedialog
  File "/home/umesha/local/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
Exception in thread Thread-2:
Traceback (most recent call last):                                                                 
  File "/home/umesha/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
     self.run()
  File "/home/umesha/local/lib/python3.9/threading.py", line 910, in run
     self._target(*self._args, **self._kwargs)
  File "/home/umesha/RC/UEC_FT-IR_UE012_2/lib/python3.9/site-packages/spectrochempy/application.py", line 208, in _check_for_updates
    version, release_date = _get_pypi_version()     
TypeError: cannot unpack non-iterable NoneType object

**Comment by atravert** [comment]
Hello,

- the compatibility with pint 0.20 should be solved soon.
-  the new error you encounter seems indeed related to tkinter, see also: #484

Can you check if tkinter is installed on your system ?: 
`import tkinter as tk`

Best regards,

**Comment by atravert** [comment]
PS: I see above that your system is  Debian, and @petsuter told us that on this system  tkinter is not available by default (see [here](https://github.com/spectrochempy/spectrochempy/discussions/484#discussioncomment-3880593) )

I think you can install it using:
`apt-get install python-tk`

**Comment by PereraUmesha** [comment]
Thank you!!!
Yes, it's Debian and i'm supposed to use python:3.9-slim.
I wonder whether there's a way to do that in my environment.

**Comment by atravert** [comment]
Pint compatibility is now solved with the last stable release.

**Comment by jfreeze95** [comment]
I am getting the same error now using the latest Pint on Mac OS

**Here is the traceback:**
Traceback (most recent call last):
  File "/Users/jfreezecp/Desktop/Research/ml-tools/CoordinateScan/CoordinateScanner.py", line 7, in <module>
    from pint.measurement import _Measurement
ModuleNotFoundError: No module named 'pint.measurement'

**Here is the environment:**
# Name                    Version                   Build  Channel
ambertools                24.8            cuda_None_nompi_py313h224bcc0_101    conda-forge
amberutils                21.0                     pypi_0    pypi
anyio                     4.9.0              pyh29332c3_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_1    conda-forge
argon2-cffi               25.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py313h20a7fcf_5    conda-forge
arpack                    3.9.1           nompi_h1f29f7c_102    conda-forge
arrow                     1.3.0              pyhd8ed1ab_1    conda-forge
ase                       3.25.0             pyhd8ed1ab_0    conda-forge
asttokens                 3.0.0              pyhd8ed1ab_1    conda-forge
async-lru                 2.0.5              pyh29332c3_0    conda-forge
attrs                     25.3.0             pyh71513ae_0    conda-forge
babel                     2.17.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.13.4             pyha770c72_0    conda-forge
bleach                    6.2.0              pyh29332c3_4    conda-forge
bleach-with-css           6.2.0                h82add2a_4    conda-forge
blinker                   1.9.0              pyhff2d567_0    conda-forge
blosc                     1.21.6               h7dd00d9_1    conda-forge
brotli                    1.1.0                h5505292_3    conda-forge
brotli-bin                1.1.0                h5505292_3    conda-forge
brotli-python             1.1.0           py313h928ef07_3    conda-forge
bzip2                     1.0.8                h99b78c6_7    conda-forge
c-ares                    1.34.5               h5505292_0    conda-forge
c-blosc2                  2.17.1               h9cbb436_0    conda-forge
ca-certificates           2025.4.26            hbd8a1cb_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                6.0.0              pyhd8ed1ab_0    conda-forge
cairo                     1.18.4               h6a3b0d2_0    conda-forge
certifi                   2025.4.26          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py313hc845a76_0    conda-forge
chardet                   5.2.0              pyhd8ed1ab_3    conda-forge
charset-normalizer        3.4.2              pyhd8ed1ab_0    conda-forge
click                     8.2.1              pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
comm                      0.2.2              pyhd8ed1ab_1    conda-forge
contourpy                 1.3.2           py313h0ebd0e5_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_1    conda-forge
cyrus-sasl                2.1.27               h60b93bd_7    conda-forge
debugpy                   1.8.14          py313h928ef07_0    conda-forge
decorator                 5.2.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dftd4                     3.7.0                hb2259e6_3    conda-forge
edgembar                  3.0                      pypi_0    pypi
exceptiongroup            1.3.0              pyhd8ed1ab_0    conda-forge
executing                 2.2.0              pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          nompi_h6637ab6_110    conda-forge
flask                     3.1.1              pyhd8ed1ab_0    conda-forge
flexcache                 0.3                pyhd8ed1ab_1    conda-forge
flexparser                0.4                pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h1383a14_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.58.2          py313ha9b7d5b_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_1    conda-forge
freetype                  2.13.3               hce30654_1    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
greenlet                  3.2.3           py313h928ef07_0    conda-forge
h11                       0.16.0             pyhd8ed1ab_0    conda-forge
h2                        4.2.0              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               h2ee6834_7    conda-forge
hdf5                      1.14.3          nompi_ha698983_109    conda-forge
hpack                     4.1.0              pyhd8ed1ab_0    conda-forge
httpcore                  1.0.9              pyh29332c3_0    conda-forge
httpx                     0.28.1             pyhd8ed1ab_0    conda-forge
hyperframe                6.1.0              pyhd8ed1ab_0    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
importlib-metadata        8.7.0              pyhe01879c_1    conda-forge
importlib_resources       6.5.2              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.5             pyh57ce528_0    conda-forge
ipython                   9.3.0              pyhfa0c392_0    conda-forge
ipython_genutils          0.2.0              pyhd8ed1ab_2    conda-forge
ipython_pygments_lexers   1.1.1              pyhd8ed1ab_0    conda-forge
ipywidgets                7.8.5              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_1    conda-forge
itsdangerous              2.2.0              pyhd8ed1ab_1    conda-forge
jedi                      0.19.2             pyhd8ed1ab_1    conda-forge
jinja2                    3.1.6              pyhd8ed1ab_0    conda-forge
joblib                    1.5.1              pyhd8ed1ab_0    conda-forge
json5                     0.12.0             pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py313h8f79df9_1    conda-forge
jsonschema                4.24.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2025.4.1           pyh29332c3_0    conda-forge
jsonschema-with-format-nongpl 4.24.0               hd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhe01879c_2    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_1    conda-forge
jupyter_core              5.8.1              pyh31011fe_0    conda-forge
jupyter_events            0.12.0             pyh29332c3_0    conda-forge
jupyter_server            2.16.0             pyhe01879c_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_1    conda-forge
jupyterlab                4.4.3              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_2    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        1.1.11             pyhd8ed1ab_0    conda-forge
khronos-opencl-icd-loader 2024.10.24           h5505292_1    conda-forge
kiwisolver                1.4.8           py313h313beb8_0  
krb5                      1.21.3               h237132a_0    conda-forge
lcms2                     2.17                 h7eeda09_0    conda-forge
lerc                      4.0.0                hd64df32_1    conda-forge
libaec                    1.1.3                hebf3989_0    conda-forge
libblas                   3.9.0           31_h10e41b3_openblas    conda-forge
libboost                  1.86.0               hc9fb7c5_3    conda-forge
libboost-python           1.86.0          py313h4e4fec1_3    conda-forge
libbrotlicommon           1.1.0                h5505292_3    conda-forge
libbrotlidec              1.1.0                h5505292_3    conda-forge
libbrotlienc              1.1.0                h5505292_3    conda-forge
libcblas                  3.9.0           31_hb3479ef_openblas    conda-forge
libcurl                   8.14.1               h73640d1_0    conda-forge
libcxx                    20.1.6               ha82da77_0    conda-forge
libdeflate                1.24                 h5773f1b_0    conda-forge
libedit                   3.1.20250104    pl5321hafb1f1b_0    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.7.0                h286801f_0    conda-forge
libffi                    3.4.6                h1da3d7d_1    conda-forge
libfreetype               2.13.3               hce30654_1    conda-forge
libfreetype6              2.13.3               h1d14073_1    conda-forge
libgfortran               14.2.0             heb5dd2a_105    conda-forge
libgfortran5              14.2.0             h2c44a93_105    conda-forge
libglib                   2.84.2               hbec27ea_0    conda-forge
libiconv                  1.18                 hfe07756_1    conda-forge
libintl                   0.24.1               h493aca8_0    conda-forge
libjpeg-turbo             3.1.0                h5505292_0    conda-forge
liblapack                 3.9.0           31_hc9a63f6_openblas    conda-forge
liblzma                   5.8.1                h39f12f2_2    conda-forge
libmpdec                  4.0.0                h5505292_0    conda-forge
libnetcdf                 4.9.2           nompi_h610d594_116    conda-forge
libnghttp2                1.64.0               h6d7220d_0    conda-forge
libntlm                   1.8                  h5505292_0    conda-forge
libopenblas               0.3.29          openmp_hf332438_0    conda-forge
libpng                    1.6.47               h3783ad8_0    conda-forge
libpq                     17.5                 h6896619_0    conda-forge
librdkit                  2025.03.3            hab0a279_0    conda-forge
libsodium                 1.0.20               h99b78c6_0    conda-forge
libsqlite                 3.50.1               h3f77e49_0    conda-forge
libssh2                   1.11.1               h1590b86_0    conda-forge
libtiff                   4.7.0                h2f21f7c_5    conda-forge
libwebp-base              1.5.0                h2471fea_0    conda-forge
libxcb                    1.17.0               hdb1d25a_0    conda-forge
libxml2                   2.13.8               h52572c6_0    conda-forge
libzip                    1.11.2               h1336266_0    conda-forge
libzlib                   1.3.1                h8359307_2    conda-forge
llvm-openmp               20.1.6               hdb05f8b_0    conda-forge
lz4-c                     1.10.0               h286801f_1    conda-forge
markupsafe                3.0.2           py313ha9b7d5b_1    conda-forge
matplotlib                3.10.3          py313h39782a4_0    conda-forge
matplotlib-base           3.10.3          py313haaf02c0_0    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_1    conda-forge
mctc-lib                  0.3.2                h0baf896_1    conda-forge
mda-xdrlib                0.2.0              pyhd8ed1ab_1    conda-forge
mdtraj                    1.10.3          py313h324e7bb_0    conda-forge
mistune                   3.1.3              pyh29332c3_0    conda-forge
mmpbsa-py                 16.0                     pypi_0    pypi
multicharge               0.3.0                hb2259e6_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.10.2             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.6             pyh29332c3_0    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_1    conda-forge
ncurses                   6.5                  h5e97a16_3    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_1    conda-forge
netcdf-fortran            4.6.1           nompi_hb61fc8b_108    conda-forge
networkx                  3.5                pyhe01879c_0    conda-forge
notebook                  7.4.3              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_1    conda-forge
numexpr                   2.10.2          py313ha6fd940_0    conda-forge
numpy                     2.3.0           py313h41a2e72_0    conda-forge
ocl_icd_wrapper_apple     1.0.0                h27ca646_0    conda-forge
opencl-headers            2024.10.24           h286801f_0    conda-forge
openff-amber-ff-ports     0.0.4              pyhca7485f_0    conda-forge
openff-forcefields        2024.09.0          pyhff2d567_0    conda-forge
openff-interchange        0.2.2              pyhd8ed1ab_0    conda-forge
openff-interchange-base   0.2.2              pyhd8ed1ab_0    conda-forge
openff-toolkit            0.12.1             pyhd8ed1ab_2    conda-forge
openff-toolkit-base       0.12.1             pyhd8ed1ab_2    conda-forge
openff-units              0.1.8              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.15             pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.3                h8a3d83b_0    conda-forge
openldap                  2.6.10               hbe55e7a_0    conda-forge
openmm                    8.2.0           py313hfe8edb3_3_khronos    conda-forge
openssl                   3.5.0                h81ee809_1    conda-forge
overrides                 7.7.0              pyhd8ed1ab_1    conda-forge
packaging                 25.0               pyh29332c3_1    conda-forge
packmol-memgen            2025.1.29                pypi_0    pypi
pandas                    2.3.0           py313h668b085_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panedr                    0.8.0              pyhd8ed1ab_1    conda-forge
parmed                    4.3.0           py313h70a7ac0_1    conda-forge
parso                     0.8.4              pyhd8ed1ab_1    conda-forge
pcre2                     10.45                ha881caa_0    conda-forge
pdb4amber                 22.0                     pypi_0    pypi
perl                      5.32.1          7_h4614cfb_perl5    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_1    conda-forge
pickleshare               0.7.5           pyhd8ed1ab_1004    conda-forge
pillow                    11.2.1          py313hb37fac4_0    conda-forge
pint                      0.24.4             pyhd8ed1ab_1    conda-forge
pip                       25.1.1             pyh145f28c_0    conda-forge
pixman                    0.46.0               h2f9eb0b_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_2    conda-forge
platformdirs              4.3.8              pyhe01879c_0    conda-forge
prometheus_client         0.22.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.51             pyha770c72_0    conda-forge
psutil                    7.0.0           py313h90d716c_0    conda-forge
pthread-stubs             0.4               hd74edd7_1002    conda-forge
ptyprocess                0.7.0              pyhd8ed1ab_1    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_1    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_1    conda-forge
pycairo                   1.28.0          py313h4109515_0    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pydantic                  1.10.21         py313h2de3ae1_0    conda-forge
pyedr                     0.8.0              pyhd8ed1ab_1    conda-forge
pygments                  2.19.1             pyhd8ed1ab_0    conda-forge
pymsmt                    22.0                     pypi_0    pypi
pyobjc-core               11.0            py313hb6afeec_0    conda-forge
pyobjc-framework-cocoa    11.0            py313hb6afeec_0    conda-forge
pyparsing                 3.2.3              pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha55dd90_7    conda-forge
pytables                  3.10.2          py313h678a918_2    conda-forge
python                    3.13.3          h81fe080_101_cp313    conda-forge
python-constraint         1.4.0              pyhff2d567_1    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_1    conda-forge
python-fastjsonschema     2.21.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2025.2             pyhd8ed1ab_0    conda-forge
python_abi                3.13                    7_cp313    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2025.2             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py313ha9b7d5b_2    conda-forge
pyzmq                     26.4.0          py313he6960b1_0    conda-forge
qhull                     2020.2               h420ef59_5    conda-forge
rdkit                     2025.03.3       py313h5971104_0    conda-forge
readline                  8.2                  h1d1bf99_2    conda-forge
referencing               0.36.2             pyh29332c3_0    conda-forge
reportlab                 4.4.1           py313h90d716c_0    conda-forge
requests                  2.32.4             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_1    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
rpds-py                   0.25.1          py313hf3ab51e_0    conda-forge
sander                    22.0                     pypi_0    pypi
scipy                     1.15.2          py313h9a24e0a_0    conda-forge
send2trash                1.8.3              pyh31c8845_1    conda-forge
setuptools                80.9.0             pyhff2d567_0    conda-forge
simple-dftd3              1.2.1                hb42fc24_0    conda-forge
six                       1.17.0             pyhd8ed1ab_0    conda-forge
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.2.1                h98b9ce2_1    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_1    conda-forge
soupsieve                 2.7                pyhd8ed1ab_0    conda-forge
sqlalchemy                2.0.41          py313h90d716c_0    conda-forge
stack_data                0.6.3              pyhd8ed1ab_1    conda-forge
tblite                    0.4.0                hb2259e6_1    conda-forge
terminado                 0.18.1             pyh31c8845_0    conda-forge
tinycss2                  1.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h892fb3f_2    conda-forge
toml-f                    0.4.2                h64a7517_2    conda-forge
tomli                     2.2.1              pyhd8ed1ab_1    conda-forge
tornado                   6.5.1           py313h90d716c_0    conda-forge
tqdm                      4.67.1             pyhd8ed1ab_1    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_1    conda-forge
types-python-dateutil     2.9.0.20250516     pyhd8ed1ab_0    conda-forge
typing-extensions         4.14.0               h32cad80_0    conda-forge
typing_extensions         4.14.0             pyhe01879c_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_1    conda-forge
tzdata                    2025b                h78e105d_0    conda-forge
uncertainties             3.2.3                    pypi_0    pypi
uri-template              1.3.0              pyhd8ed1ab_1    conda-forge
urllib3                   2.4.0              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_1    conda-forge
webcolors                 24.11.1            pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_3    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_1    conda-forge
werkzeug                  3.1.3              pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.6.10             pyhd8ed1ab_0    conda-forge
xmltodict                 0.14.2             pyhd8ed1ab_1    conda-forge
xorg-libice               1.1.2                h5505292_0    conda-forge
xorg-libsm                1.2.6                h5505292_0    conda-forge
xorg-libx11               1.8.12               h6a5fb8c_0    conda-forge
xorg-libxau               1.0.12               h5505292_0    conda-forge
xorg-libxdmcp             1.1.5                hd74edd7_0    conda-forge
xorg-libxext              1.3.6                hd74edd7_0    conda-forge
xorg-libxt                1.3.1                h5505292_0    conda-forge
xtb                       6.7.1                h8d23caa_2    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zeromq                    4.3.5                hc1bb282_7    conda-forge
zipp                      3.23.0             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h8359307_2    conda-forge
zlib-ng                   2.2.4                h13dfb9a_0    conda-forge
zstandard                 0.23.0          py313h90d716c_2    conda-forge
zstd                      1.5.7                h6491c7d_2    conda-forge

**Comment by atravert** [comment]
Hello @jfreeze95,

The error you're encountering does not appear to stem from SpectroChemPy but is more likely associated with the script `CoordinateScan/CoordinateScanner.py` that you're using.  You should conatct the developer of that script for further assistance.
