### ISSUE TITLE
[Bug]: List index out of range on OPUS FTIR file read-in

### ISSUE THREAD

**Issue by ManusGit9** [spectrochempy/spectrochempy#565]
### What happened?

I am trying to plot a FTIR dataset recorded using a Bruker Vertex 80v (-> OPUS). The python script already fails at the read-in of the file into a NDDataset.

### What did you expect to happen?

I would have expected no error at this stage, since i was able to read in similar files from the same machine in a previous version of spectrochempy. However in the old version i recently got a different error message, so i updated spectrochempy.

### Minimal Complete Verifiable Example

```python
import spectrochempy as scp
import os


filepath_KOH = str( os.getcwd() ) + "2023-01-26_M010SCAO_KOH_50deg_MCT_after1stCV_CA_564mV_SSC.0"

dataset = scp.NDDataset.read_opus( filepath_KOH )
```

### Relevant log output

```python
Traceback (most recent call last):

  File "/home/manuel/spectrochempy-install/anaconda3/envs/scpy/lib/python3.10/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/manuel/Dokumente/03_Master_Thesis/Evaluation_Skripts/Python_Project_Master/OPUS_plotting_Standalone.ipy", line 19, in <module>
    dataset = scp.NDDataset.read_opus( [ datapath_4_KOH ])

  File "/home/manuel/spectrochempy-install/anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/readers/read_opus.py", line 161, in read_opus
    return importer(*paths, **kwargs)

  File "/home/manuel/spectrochempy-install/anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/readers/importer.py", line 133, in __call__
    self._switch_protocol(key, self.files, **kwargs)

  File "/home/manuel/spectrochempy-install/anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/readers/importer.py", line 204, in _switch_protocol
    res = read_(self.objtype(), filename, **kwargs)

  File "/home/manuel/spectrochempy-install/anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/readers/read_opus.py", line 171, in _read_opus
    debug_("Bruker OPUS import")

  File "/home/manuel/spectrochempy-install/anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/__init__.py", line 76, in debug_
    stg = _format_args("", "DEBUG: ", *args, **kwargs)

  File "/home/manuel/spectrochempy-install/anaconda3/envs/scpy/lib/python3.10/site-packages/spectrochempy/core/__init__.py", line 44, in _format_args
    app.log.handlers[1].setFormatter(formatter)

IndexError: list index out of range
```

### Anything else we need to know?

I am using Spyder through Anaconda:
* Spyder version: 5.3.3  (conda)
* Python version: 3.10.6 64-bit
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Linux 5.15.0-58-generic

Recently i updated Spyder manually, because i had other errors occurring in different scripts (which were apparently linked to the version of Spyder being outdated) and Anaconda did not automatically provide the latest version of Spyder.

I think it is necessary for me to send you the data file. Please tell me if this would be helpful and which method you would prefer.

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
python-bits: 64
OS: Linux
OS-release: 5.15.0-58-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: ('en_US', 'UTF-8')

quadprog: 0.1.11
brukeropusreader: 1.3
quaternion: 2022.4.1
cantera: None
colorama: 0.4.5
dill: 0.3.5.1
ipython: None
jinja2: 3.0.3
matplotlib: 3.5.2
numba: 0.55.0
numpy: 1.21.5
pint: 0.19.2
requests: 2.28.1
scipy: 1.7.3
tqdm: 4.64.1
traitlets: 5.1.1
traittypes: 0.2.1
xlrd: 2.0.1
pyyaml: None
ipywidgets: 8.0.2
ipympl: 0.9.2
setuptools: 65.3.0
setuptools_scm: 7.0.5
git: None
jupyterlab: 3.4.7
nodejs: None
pytest: None
pytest-doctestplus: None
pytest-flake8: None
pytest-mock: None
pyfakefs: None
scikit-image: None
coverage: None
black: 22.8.0
pre-commit: None
cffconvert: None
mamba: 0.25.0
jupytext: None
sphinx: 5.1.1
sphinx_rtd_theme: None
autodocsumm: None
sphinx-gallery: None
nbsphinx: None
jupyter_sphinx: None
json5: 0.9.5
sphinx-copybutton: None
numpydoc: 1.4.0
pandoc: None
conda-build: None
conda-verify: None
anaconda-client: None
xarray: None
scikit-learn: None
dash: None
dash-bootstrap-components: None
dash: None
daq: None
jupyter-dash: None
plotly: None
pip: 22.2.2
autodoc_traits: None
dash_defer_js_import: None
dash-ace: None
spectrochempy: 0.4.10

**Comment by atravert** [comment]
Can you run your script  in a jupyter notebook (i.e. without spyder) ?   If this still doesn't work , then please provide a link to download the opus file: we will check it.

**Comment by fernandezc** [comment]
Maybe it's a bug with the logging system (as far as I can tell from the error message). Is it  possible to upgrade spectrochempy to the last version 0.5.1 and see it it still happens.

**Comment by fernandezc** [comment]
In addition, can you check if you have the log file created in you HOME directory  "~/.spectrochempy/logs/spectrochempy.log?

**Comment by fernandezc** [comment]
@ManusGit9 Hello, 
Regarding the logs you produced, I suspect that this is due to a misconfiguration (due to recent changes) of the logging system. I have already worked on the upcoming 0.6 version of spectrochempy, so I decided to include the logging system changes in the current master development branch. I would be glad if you try it on your file to see if it solves the problems. 

To install this dev version, use: 
`conda install -c "spectrocat/label/dev" spectrochempy`. 

Hopefully it will help, and  thanks for raising the issue! We are only 2 to develop this program at the moment, so it is not always easy to test all situations. 

If you still have problems with the logger during execution, you may need to reset the configuration by simply deleting the file: 
`~/.spectrochempy/config/spectrochempy_cfg.py`

CF

**Comment by fernandezc** [comment]
Update:  Now the configuration files have been splitter in several files. To put everything in the default configuration, just delete the ~/.spectrochempy/config/  directory and run again spectrochempy, default files will be recreated. 

@ManusGit9 Please tell me if upgrading to the dev version has solved your problem so I can close this issue. If not please tell me. This can help other people. Thanks in advance.

**Comment by fernandezc** [comment]
I think this is now solved. Feel free to reopen the issue if it is not the case.

**Comment by ManusGit9** [comment]
Hello Christian,yes, as i wrote in my last mail it was working in the (then) current version, the last time i checked. I didn't have time yet to test it for the in-develppment version, but i will let you know, once i have tested it in the dev-version as well.Thank you and kind RegardsManuelAm 10.03.23, 19:52 schrieb Christian Fernandez ***@***.***>:

   
  I think this is now solved. Feel free to reopen the issue if it is not the case.

**Comment by fernandezc** [comment]
Thanks for the feedback. Since the opening of the issues there was new release so you normally don't need now to use the dev version. Just upgrade to 0.5.4. 
Best regards
