### ISSUE TITLE
Issues reading SPC file contents into Dash App with scp.read_spc(content=content)

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#571]
### Discussed in https://github.com/spectrochempy/spectrochempy/discussions/570

<div type='discussions-op-text'>

<sup>Originally posted by **seand412** February  6, 2023</sup>
Hi, I'm trying to create a Dash app which requires reading of SPC spectral files. Due to the quirks of Dash, I can't pass a file location, I have to read in the file contents. SpectroChemPy docs for the `scp.read_spc()` function (and other reads) state I can use the `content` kwarg to pass a bytes object instead. When I try (in a Jupyter notebook) though, I get an error message that states "ERROR | TypeError: 'WindowsPath' object is not subscriptable." in a red error box under the executed cell. There's no traceback provided. 

The docs state there are examples on how to do what I'm trying in the `tests/test_readers` directory, but in my environment I can't find this directory. And the `test_read_spc.py` file that I found in an older version online just has a bunch of Assert tests to ensure files were read properly, not any examples on how to read spc file contents.

The file I'm trying to read is an SPC file, I read the bytes contents of it with `with open(file, 'rb') as f: content = f.read()`. I try reading the contents with `f = scp.read_spc(content=content)`. Then I get the TypeError issue.

Any help would be much appreciated, let me know if you need more info and I'll see what I can do.

Thanks!</div>

**Comment by fernandezc** [comment]
Hi, Indeed it is possible to open NDDataset in Dash,. I had already made a version (but for lack of time, I left it aside for the moment issue #149). Interesting that you have this idea... maybe there is a way to collaborate on it.

I have a branch that implements all this but it is completely out of sync with the main branch: I'll have to look at it closely when I have a minimum of time to synchronize it to the main branch (master): https://github.com/spectrochempy/spectrochempy/tree/feature/dash.

I'll give you a more complete answer on how to use content, but I'll have to look at it... I'm not sure if it's been implemented for all readers (SPC being quite recent).

**Comment by fernandezc** [comment]
You can find the way for reading content in this file in the master branch : 
[tests/test_core/test_readers/test_importer.py](https://github.com/spectrochempy/spectrochempy/blob/master/tests/test_core/test_readers/test_importer.py)

around line 302.

Hope it helps.

**Comment by seand412** [comment]
Hi Christian, first off thanks for the prompt response, I greatly appreciate you taking the time. Unfortunately I'm still pretty confused.

The line you mention reads `nd = read({"somename.fk": "a fake content"})`, where the `read` function is `spectrochempy.core.readers.importer.read`, i.e. `scp.read()` , which I think is just the generic version of `scp.read_spc()`. So I believe you are suggesting passing in a dictionary with the contents of the spc file? I run into two issues with this:

(1) I don't have a dictionary of the file contents available to pass, that's of course why I'm trying to read the spc. My Dash app will have no knowledge of the input SPC file before trying to load it in, except the local path of the file on the user's local machine that the user specifies.
(2) Even when trying to `scp.read` a dictionary as shown, I get a NoneType object out: 

`from spectrochempy.core.readers.importer import read`
`test = read({'key1':'val1', 'key2':'val2'})`
`type(test)`
returns `NoneType`. 

Please see below image for an idea of the data I'm trying to interpret. I know that it can be loaded using SpectroChemPy because it works when passing the file location `file` to `scp.read()`. But of course, as mentioned, I can't do that in Dash.
![image](https://user-images.githubusercontent.com/124622799/217101695-0c070768-572a-4b31-9776-94b7e3eadb30.png)

I could also be misinterpreting your answer, if so could you please clarify. 

Thanks again!

**Comment by seand412** [comment]
Edit: I just figured out I can change the log level in this module, here's the traceback of the original "'WindowsPath' object is not subscriptable" error:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[86], line 1
----> 1 f = scp.read(content=content)

File ~\miniconda3\envs\dash2\lib\site-packages\spectrochempy\core\readers\importer.py:444, in read(*paths, **kwargs)
    441     except KeyError:
    442         raise ProtocolError(protocol, list(importer.protocols.values()))
--> 444 return importer(*paths, **kwargs)

File ~\miniconda3\envs\dash2\lib\site-packages\spectrochempy\core\readers\importer.py:131, in Importer.__call__(self, *args, **kwargs)
    128     if len(self.datasets) > 1:
    129         self.datasets = self._do_merge(self.datasets, **kwargs)
--> 131 elif key and key[1:] not in list(zip(*FILETYPES))[0] + list(zip(*ALIAS))[0]:
    132     raise TypeError(f"Filetype `{key}` is unknown in spectrochempy")
    133 else:
    134     # here files are read / or remotely from the disk using filenames

TypeError: 'WindowsPath' object is not subscriptable

`

**Comment by fernandezc** [comment]
No problem, it was not clear. And definitely we need to update the doc (with some example).
This works:
<img width="539" alt="Image" src="https://user-images.githubusercontent.com/2428474/217107235-644cf980-2008-46ca-9daa-b75866e52306.png">

**Comment by seand412** [comment]
AHA! That was exactly what I needed, thank you so much!

Some clarifying points that should be noted for posterity: 

(1) In the dash app, you can't use the `with open(file, 'rb') as f: content = f.read()` method, as `file` here is still the path to the file, which Dash doesn't know. Instead, use the method that is described in the Dash dcc.Upload documentation, namely:

`content_type, content_string = contents.split(',')`
`decoded = base64.b64decode(content_string)`

The two lines above give you `decoded`, which is the same bytes object as `content` pictured in my previous comment. 

(2) Then you can use the dictionary read method from Christian above, as follows:
`nd = scp.read({filename:decoded})`
where `filename` comes from an `@app.callback(<output>, <input>, State('upload-data', 'filename')` callback input. I suppose this could be any old string you want, but above is how you can keep the file name.

Cheers!

**Comment by fernandezc** [comment]
This is exactly the reason why I introduced "content" in the read function to be able to use it in a callback. 

https://github.com/spectrochempy/spectrochempy/blob/feature/dash/spectrochempy/gui/callbacks.py

  
```python
def parse_upload_contents(filename, contents, single=False):
    #
    # transform uploaded content to a NDDataset
    #
    content_type, content_string = contents.split(",")
    decoded = base64.b64decode(content_string)
    ds = scp.read(filename, content=decoded)
    return ds
```
By the way, in fact it is not necessary to use a dict for a single file

```python
scp.read(filename, content=decoded)
```
also works. 

The file name just needs to have the `.spc` extension in your case (corresponding to the reader protocol) even if you replace `read` with `read_spc`. I might change that to allow an arbitrary name... 
I think `read` is better to allow the dash application to work with different file formats.

Using dictionaries should allow the application to work with multiple file selections (untested!)

**Comment by fernandezc** [comment]
@seand412, Hi, I am closing this issue now as it seems to be resolved. Do not hesitate to reopen it if it is necessary for example to adapt the reader for particular needs.

**Comment by seand412** [comment]
Thanks for the additional details. You can indeed close this issue out, I've got what I need for now.
