### ISSUE TITLE
[Bug]: scpy changes matplotlib backend when run in pycharm and VS code 

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#577]
### What happened?

on windows, NDDataset.plot() does not work in pycharm (normal mode or scientific mode), nor in VS code (run), but does work in Ipython console or jupyer.

The bug is present since v.0.4.11.dev5+g11449a239 (commit massage:  "WIP code/docs maintenance (+1 squashed commit)").. The reason for this seems that importing scpy change the backend to 'template' ??? (see example below)

### Minimal Complete Verifiable Example

```python
from matplotlib import get_backend
print(get_backend())
import spectrochempy as scp
print(get_backend())
```

### Relevant log output

```python
backend BEFORE importing SCPY : module://backend_interagg
Loading SpectroChemPy API: 100%|██████████| 100.0/100 [00:01<00:00, 70.05it/s]
SpectroChemPy's API - v.0.4.11.dev5+g11449a239
© Copyright 2014-2023 - A.Travert & C.Fernandez @ LCS
 backend AFTER importing SCPY : template
```

### Anything else we need to know?

the code above leads to the expected output before the commit   `11449a239`

```
backend BEFORE importing SCPY : module://backend_interagg
Loading SpectroChemPy API: 100%|██████████| 100.0/100 [00:01<00:00, 75.84it/s]
SpectroChemPy's API - v.0.4.11.dev3+g3dc2a9fce
© Copyright 2014-2023 - A.Travert & C.Fernandez @ LCS
 backend AFTER importing SCPY : module://backend_interagg
```

same thing happens with VSCode (backend: QtAgg,  but it works fine when runing in VS Code/interactive window or  jupyer notebooks:

![image](https://user-images.githubusercontent.com/10098314/218108535-9f6d5898-4a8f-4070-b010-8bdc97600a73.png)

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'ISO8859-1')

quadprog: 0.1.11
brukeropusreader: 1.3
numpy-quaternion: None
cffconvert: 2.0.0
colorama: 0.4.6
dill: 0.3.6
ipython: None
jinja2: 3.1.2
matplotlib: 3.6.2
numba: 0.56.4
numpy: 1.23.5
numpydoc: 1.5.0
pint: 0.20.1
pytz: 2022.7.1
requests: 2.28.1
scipy: 1.9.3
tqdm: 4.64.1
traitlets: 5.8.0
traittypes: 0.2.1
xlrd: 2.0.1
pyyaml: None
ipywidgets: 8.0.4
widgetsnbextension: 4.0.5
jupyterlab_widgets: 3.0.5
ipympl: 0.9.2
setuptools: 65.6.3
setuptools_scm: 7.1.0
gitpython: None
jupyterlab: 3.5.2
nodejs: 0.1.1
pytest: 7.2.1
pytest-doctestplus: None
pytest-flake8: None
pytest-mock: None
pyfakefs: None
pep8-naming: None
scikit-image: None
coverage: None
black: 23.1.0
pre-commit: None
mamba: None
docrep: None
jupytext: None
sphinx==5.3: None
sphinx_rtd_theme==1.1: None
autodocsumm: None
sphinx-gallery: None
nbsphinx: None
jupyter_sphinx: None
json5: 0.9.5
sphinx-copybutton: None
pandoc: None
autodoc_traits: None

​

**Comment by fernandezc** [comment]
J4ai regardé vite-fait, mais je ne vois pas de changements notable dans le fichier spectrochempy/api.py ou les backend sont définis. Peut etre que c'est lié à la version de matplotlib. Peut etre essayer de prendre une version inférieure ???

**Comment by fernandezc** [comment]
Bon en effet le bckend est changé après l'import du core. Je regarde pourquoi!

**Comment by fernandezc** [comment]
Done, le problème était dans le fichiers utils/docstrings.py !
