### ISSUE TITLE
[Bug]: plt.plot fails when importing matplotlib and spectrochempy at the same time

### ISSUE THREAD

**Issue by LightAQA** [spectrochempy/spectrochempy#591]
### What happened?

When importing matplotlib.pyplot and spectrochempy at the same time, plt.plot cannot produce drawing results. At the same time, the running time becomes longer, and there is no error message.

### Environment

SpectroChemPy's API - v.0.5.1

**Comment by fernandezc** [comment]
Thank you for reporting this. 
Can you tell us a little bit more about it with a minimal example that we could reproduce? For example, in what order do you do the import?

**Comment by LightAQA** [comment]
such as:
import matplotlib.pyplot as plt
import spectrochempy as scp

x=[1,2,3,4,5]
y=[5,4,3,2,1]
plt.plot(x,y)
plt.show()

**Comment by fernandezc** [comment]
I did a fresh install of spectrochempy in a new conda environment, opened ipython in a terminal, and typed your code: 
For me there is no problem: the plot is shown. 
 
It would be nice to have the output of scp.show_versions() but unfortunately, here there is a bug that I have to fix. 
Meanwhile, may be you could tell me on with machine/OS you work, the matplotlib version, do you use conda or pip to install spectrochempy? do you work on a dedicated environment?

**Comment by fernandezc** [comment]
OK I think I found it. 
Please upgrade spectrochempy  to version 5.2.  I remember now there was a bug in 5.1, now corrected.

**Comment by fernandezc** [comment]
And it seems that the pypi repository was not updated to the last 0.5.2 version. If you use pip it can be a problem actually. I am going the fix this today.

**Comment by fernandezc** [comment]
You can now use 0.5.3 version on both pypi and conda repository. It should solve the plot problem. If not please add the relevant information here. In principle, you can now use `scp.show_versions()` to report your environment.

**Comment by fernandezc** [comment]
> You can now use 0.5.3 version on both pypi and conda repository. It should solve the plot problem. If not please add the relevant information here. In principle, you can now use `scp.show_versions()` to report your environment.

UPDATE: 0.5.3 was buggy. Last release 0.5.4 should be OK.
