### ISSUE TITLE
[Docs] : The introduction page is not displayed correctly

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#632]
### What happened?

https://www.spectrochempy.fr//stable/userguide/introduction/introduction.html. is not displayed correctly 

I could not find why for now.

### What did you expect to happen?

-

### Environment

-

**Comment by atravert** [comment]
could be related to this ?:

https://github.com/spectrochempy/spectrochempy/actions/runs/4799938248/jobs/8540228483#step:8:447

**Comment by fernandezc** [comment]
What do you mean by this? 

If I remove the title: 

 # ## NDDataset, the main object. 

on line 115 of the introduction.py file, it works.
 I really don't understand why the html output is incorrect when this line is here. It looks ok to me.

**Comment by atravert** [comment]
Strange indeed...
