### ISSUE TITLE
[Bug]:documention, find peaks 

### ISSUE THREAD

**Issue by Shashi-kadam** [spectrochempy/spectrochempy#663]
### What happened?

The plots in the [find peaks tutorial](https://www.spectrochempy.fr/latest/userguide/analysis/peak_finding.html) look strange. The peak maxima are not correctly indicated. 

![image](https://github.com/spectrochempy/spectrochempy/assets/26969955/53edb6ef-7854-4d43-aa09-4f2639955733)

### Environment

N/A

**Comment by atravert** [comment]
Thank you Shashi, I will look at this asap.

**Comment by fernandezc** [comment]
PR #669 solve this problem.
