### ISSUE TITLE
[Bug]: inconsistent coordinates when slicing by list of indexes 

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#668]
### What happened?

slicing a NDDataset using a list of indexes (e.g. D[[1, 5, 8,  10]]) yields a NDDataset with incorrect coordinates for the inner indexes (here the coordinate corresponding to indexes 5 and 8). Given first and last coordinates (here 1 and 10) and the number of indexes the returned coordinates are the same when changing the inner indexes (within [first index, last index]).    

This is probably related to the recent change in linear coord, and causes, for instance, issue #663

### What did you expect to happen?

`D[[1, 5, 8,  10]].x` should return the same as `D.x[1, 5, 8,  10]`

### Minimal Complete Verifiable Example

```python
# %%
import spectrochempy as scp

s = scp.read("irdata/CO@Mo_Al2O3.SPG")[-1,2300.:1900.]

print(s[:, [0, 1, 2, 7, 15]].x.data)  # wrongly returns [    2300     2296     2293     2289     2285]
print(s[:, [0, 1, 5, 10, 15]].x.data)  # despite the change of inner index, it returns the same as above... 
print(s.x[[0, 1, 2, 7, 15]].data) # returns the expected values of the first line above[    2300     2299     2298     2293     2285]
```

### Environment

INSTALLED VERSIONS
------------------
commit: 606431ce4d3bd67de6fef87d65fac266036ecf2c
python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'ISO8859-1')
quadprog: 0.1.11
brukeropusreader: 1.3
numpy-quaternion: None
cffconvert: 2.0.0
colorama: 0.4.6
dill: 0.3.6
docrep: 0.3.2
ipython: None
jinja2: 3.1.2
matplotlib: 3.6.2
numba: 0.56.4
numpy: 1.23.5
numpydoc>=1.2: None
pint: 0.20.1
pytz: 2023.3
requests: 2.29.0
scipy: 1.10.1
tqdm: 4.65.0
traitlets: 5.9.0
scikit-learn: None
xlrd: 2.0.1
pyyaml: None
setuptools: 67.7.2
setuptools_scm: 7.1.0
gitpython: None
jupyterlab: 3.5.3
nodejs: 0.1.1
ipywidgets==8.0.4: None
widgetsnbextension==4.0.5: None
jupyterlab_widgets==3.0.5: None
ipympl: 0.9.3
coverage: 7.2.4
pytest: 7.3.1
pytest-doctestplus: None
pytest-flake8: None
pytest-mock: None
pyfakefs: 5.2.2
pep8-naming: None
xarray: 2023.4.2
scikit-image: None
black: 23.3.0
pre-commit: None
mamba: 1.4.2
 WARNING | (UserWarning) Sphinx Gallery in version 0.13.0 is not supported by Jupytext. Please use sphinx-gallery<=0.7.0 instead. If that is an issue, feel free to report it at https://github.com/mwouts/jupytext/issues, or even better, prepare a PR to handle the new signature of sphinx_gallery.notebook.rst2md.
jupytext: 1.14.5
sphinx==5.3: None
sphinx_rtd_theme==1.2: None
autodocsumm: 0.2.6
sphinx-gallery: None
nbsphinx: 0.9.1
jupyter_sphinx: 0.4.0
json5: 0.9.5
sphinx-copybutton: None
sphinxcontrib-bibtex: None
pandoc==2.19: None
numpydoc>=1.2: None

**Comment by fernandezc** [comment]
Indeed, the bug is due to the automatic linearization that should not occur in the present case of fancy indexing. I'll try to fix it as fast as possible.
