### ISSUE TITLE
[FEATURE]: removing cosmic rays from raman spectra

### ISSUE THREAD

**Issue by sabourizk** [spectrochempy/spectrochempy#688]
### Is your feature request related to a problem?

Right now when I plot my raman spectra, I have very clear cosmic rays that are outliers in my data

### Describe the solution you'd like

A function that removes any obvious cosmic rays

**Comment by fernandezc** [comment]
Thanks for the suggestion. 
I'm currently working on improving spectral filters, and this feature is clearly something we intended to introduce since it addresses the same type of problem. It will probably be available in the next version, say in a week or two.

**Comment by sabourizk** [comment]
Awesome! Thanks!

**Comment by fernandezc** [comment]
Hello, 
This feature has been added to the development version and will be available in the next version as soon as possible.
I hope it meets your needs. But don't hesitate to comment if you encounter any problems or have any new suggestions.
