### ISSUE TITLE
[FEATURE]: Default log level should be 'DEBUG'

### ISSUE THREAD

**Issue by cedleau** [spectrochempy/spectrochempy#716]
### Is your feature request related to a problem?

Hi,
Somewhere in the source of spectrochempy is this piece of code, which changes the way python display tracebacks.
Tracebacks are hidden unless `log_level` is `DEBUG`.
```
# ----------------------------------------------------------------------------------
    # Error/warning capture
    # ----------------------------------------------------------------------------------
    def _ipython_catch_exceptions(self, shell, etype, evalue, tb, tb_offset=None):
        # output the full traceback only in DEBUG mode or when under pytest
        if self.log_level == logging.DEBUG:
            shell.showtraceback((etype, evalue, tb), tb_offset=tb_offset)
        else:
            self.log.error(f"{etype.__name__}: {evalue}")
```
However this not only affect the errors from scp, but all of them. This issue is this `log_level` is NOT `DEBUG` by default.
Hence, all the tracebacks are hidden by default, which is a major pitfall when trying to integrate spectrochempy in a bigger script.

One a fresh install on a collegue computer, it took me more than one hour to identify that `spectrochempy` was indeed causing it, that it persists throughout several versions, and finally find how to mitigate it (`scp.set_loglevel('DEBUG')` just after import).

I think this can really discourage new users from using `spectrochempy`, which is why I would be in favor of setting this `DEBUG` level by default.
Best,
Cédric

### Describe the solution you'd like

`scp.set_loglevel('DEBUG')` should be default

**Comment by fernandezc** [comment]
Thanks Cedric for your feedback. Indeed, I understand the problem. I'll fix it for the next version. Removing the traceback was intended to avoid drowning beginners using jupyter lab, but if you're using spectrochempy as a script it's certainly not very practical.
Best 
Christian
