### ISSUE TITLE
Matplotlib widgets not working (in jupyter Lab)

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#72]
Author: @fernandezc (Christian Fernandez )

Redmine Issue: 70, https://redmine.spectrochempy.fr/issues/70

---

None

**Comment by fernandezc** [comment]
From: @fernandezc (Christian Fernandez )
Date: 2020-05-29T16:54:04Z

---

matplotlib doesn't work well with Jupiter Lab (or do not work - quite erratic behaviour). But they work with Jupyter Notebook.

**Comment by fernandezc** [comment]
Seems to be solved with last update of Jupiter widget extensions.

**Comment by Luis-jacobo** [comment]
It seems it is not possible to displaying the figures in independent windows. Default matplotlib backend is 'widget' and I can't change to 'qt' (see picture). In the graphic options is not possible to change scale range, maybe  is it a new version of matplotlib?. 
![Capture](https://user-images.githubusercontent.com/77514336/104808596-a6a7aa80-57e7-11eb-97ae-56c2634f2211.JPG)
![CAPTURE3](https://user-images.githubusercontent.com/77514336/104808669-1158e600-57e8-11eb-99a3-4b9fd74472e3.JPG)
![CAPTURE4](https://user-images.githubusercontent.com/77514336/104808699-5250fa80-57e8-11eb-8028-772ea00ad18b.JPG)

**Comment by fernandezc** [comment]
Hi Luis

Concerning the opening of external window, use in Python:

%matplotlib qt

BEFORE importing SpectroChemPy

```python
%matplotlib qt
import spectrochempy as scp
...
```

**Comment by fernandezc** [comment]
This will change in the 0.2.0, but in 0.1.22 importing SpectroChemPy is choosing a backend . And you can not change it after it easily.
So you must select the backend BEFORE importing SpectroChemPy

**Comment by Luis-jacobo** [comment]
Hi Christian,

Thank you for your help!


----- Mail d’origine -----
De: Christian Fernandez <notifications@github.com>
À: spectrochempy/spectrochempy <spectrochempy@noreply.github.com>
Cc: Luis-jacobo <luis-jacobo.aguilera@ensicaen.fr>, Comment <comment@noreply.github.com>
Envoyé: Sat, 16 Jan 2021 12:21:46 +0100 (CET)
Objet: Re: [spectrochempy/spectrochempy] Matplotlib widgets not working (in jupyter Lab) (#72)

Hi Luis

Concerning the opening of external window, use in Python:

%matplotlib qt

BEFORE importing SpectroChemPy

```python
%matplotlib qt
import spectrochempy as scp
...
```
