### ISSUE TITLE
[Bug]: fit_to_concentrations with custom temperature profiles

### ISSUE THREAD

**Issue by eleonora-vottero** [spectrochempy/spectrochempy#724]
### What happened?

When trying to run kin.fit_to_concentrations , where 'kin' was calculated from scp.ActionMassKinetics by considering a custom temperature vs time profile, I encounter the error:

` ERROR | TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'`

raised by line spectrochempy\analysis\kinetic\kineticutilities.py:522 , part of the function 'integrate'.

The line under exam is:

`t_grid = np.arange(0, t[-1] + k_dt, k_dt)   `

and the problem seem to arise from the fact that 'k_dt' wasn't assigned a value when the 'integrate' function is called in this way.

### What did you expect to happen?

That kin.fit_to_concentrations would run also in the case of custom temperature functions. 

So that the issue seems to be the definition of the k_dt for the correct integration in the case of non-isotherm systems, it could for example be useful to introduce k_dt as an argument for the fit_to_concentrations function.

### Relevant log output

```python
File c:\users\eleonora\documents\work\script esercizio\231012 test eleonora fer12.5.py:1320
    test = kin.fit_to_concentrations(dataset_3comp_bis, iexp, i2iexp, dict_param_to_optimize, ivp_solver_kwargs={'method':'Radau'})

  File ~\anaconda3\envs\scpy\lib\site-packages\spectrochempy\analysis\kinetic\kineticutilities.py:774 in fit_to_concentrations
    init_val = objective(

  File ~\anaconda3\envs\scpy\lib\site-packages\spectrochempy\analysis\kinetic\kineticutilities.py:742 in objective
    Chat = self.integrate(

  File ~\anaconda3\envs\scpy\lib\site-packages\spectrochempy\analysis\kinetic\kineticutilities.py:521 in integrate
    t_grid = np.arange(0, t[-1] + k_dt, k_dt)

TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
```

### Environment

SpectroChemPy's API - v.0.6.7
© Copyright 2014-2023 - A.Travert & C.Fernandez @ LCS

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'ISO8859-1')

brukeropusreader: 1.3
numpy-quaternion: None
cffconvert: 2.0.0
colorama: 0.4.6
dill: 0.3.7
docrep: 0.3.2
ipython: None
jinja2: 3.1.2
matplotlib: 3.8.0
numba: 0.58.1
numpy: 1.26.0
numpydoc>=1.2: None
osqp: None
packaging: 23.2
pint>=0.20: None
requests: 2.31.0
scipy: 1.11.3
tqdm: 4.66.1
traitlets==5.9.0: None
tzlocal: 5.2
scikit-learn==1.2: None
xlrd: 2.0.1
pyyaml: None
setuptools: 68.2.2
setuptools_scm: 8.0.4
gitpython: None
ipywidgets==8.0.4: None
ipympl: 0.9.3
jupyterlab: 3.5.3
jupyterlab_widgets==3.0.5: None
jupyter_server==2.7.3: None
nodejs: 0.1.1
widgetsnbextension==4.0.5: None
voila: 0.4.3
voila-material: None
coverage: None
pytest: None
pytest-doctestplus: None
pytest-flake8: None
pytest-mock: None
pyfakefs: None
pep8-naming: None
xarray: None
black: 23.10.0
boa: None
isort: 5.12.0
json5: 0.9.14
jupytext: None
jupyter_sphinx: None
mamba: 1.5.2
nbconvert==7.4.0: None
nbsphinx: None
numpydoc>=1.2: None
pandoc==2.19: None
pypandoc: None
pre-commit: None
scikit-image: None
sphinx==5.3: None
sphinx-copybutton: None
sphinx-gallery==0.13: None
sphinx_rtd_theme==1.2: None
sphinxcontrib-bibtex: None

**Comment by atravert** [comment]
Thank you for your message @eleonora-vottero

The non-isothermal part is not yet fully documented.
