### ISSUE TITLE
read_opus() shifts the xaxis

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#76]
Author: @atravert (Arnaud TRAVERT)

Redmine Issue: 75, https://redmine.spectrochempy.fr/issues/75

---

A bug in brukeropusreader module leads to a shift of the xaxis.
It has been corrected on the spectrochempy/brukeropusreader fork (PR FIX wrong setting of wavenumbers axis #1) 
but a change in read_opus() is also needed.

**Comment by fernandezc** [comment]
From: @fernandezc (Christian Fernandez )
Date: 2020-05-30T10:54:32Z

---

Is this still a bug? should we close this issue?

**Comment by atravert** [comment]
I will add a test and then close it.
