### ISSUE TITLE
[Bug]: Alignement of spectra failed.

### ISSUE THREAD

**Issue by sschusser** [spectrochempy/spectrochempy#763]
### What happened?

Trying to aligne two NDdatasets with spectra failed. I expect the error to be due to some modification on the code of a certain version of spectrochempy since my code originated from a script used with an earlier version of spectrochempy. Unfortunately, I am not able to reconstruct wich version I used with this scirpt in the past.

### What did you expect to happen?

The spectra get aligned.

### Minimal Complete Verifiable Example

```python
### Spectra
folder_list = [Path('D:\xyz\2.2'),
               Path('D:\xyz\3.4'),
               Path('D:\xyz\5.4')]
name = 'Chem1'

for folder in folder_list:
    thickness = float(folder.name)
    foundfiles = list(folder.glob('*'))
    print(thickness, len(foundfiles) )
   
    opus = scp.read_opus(foundfiles, merge=True)
    opus.name = name
    ### Debug workarround, see https://github.com/spectrochempy/spectrochempy/issues/643
    opus.x = scp.Coord(opus.x)
    opus.x.ito('nm')
    ### Setting thickness
    y = opus.y
    opus.y = np.full(y.shape, thickness)
    opus.y.units = scp.ur.micrometer
    ### Append to array
    all_opus.append(opus)

spectraconcat = scp.concatenate(all_opus, axis='y')

### Filter
Fs = scp.read_opus(F_path, merge=True)
Fs.name = 'Fe1'

# Debug workarround, see https://github.com/spectrochempy/spectrochempy/issues/643
Fs.x = scp.Coord(Fs.x)
Fs.x.ito('nm')
Fs = Fs[:, wave_lim[0]:wave_lim[1]]
Fs = Fs/Fs.max()

### Align
scp.align(spectra, Fs, method='first')
```

### Relevant log output

```python
ValueError                                Traceback (most recent call last)
Cell In[36], line 1
----> 1 scp.align(spectra,
      2           Fs,
      3           method='first')

File ~\Programme (portabel)\WPy64-31090\python-3.10.9.amd64\lib\site-packages\spectrochempy\processing\alignement\align.py:338, in align(dataset, *others, **kwargs)
    336 obj = object["obj"]
    337 # obj[np.where(np.isnan(obj))] = MASKED  # mask NaN values
--> 338 obj[
    339     np.where(np.isnan(obj))
    340 ] = 99999999999999.0  # replace NaN values (to simplify
    341 # comparisons)
    342 idx = int(object["idx"])

File ~\Programme (portabel)\WPy64-31090\python-3.10.9.amd64\lib\site-packages\spectrochempy\core\dataset\baseobjects\ndcomplex.py:679, in NDComplexArray.__setitem__(self, items, value)
    677 def __setitem__(self, items, value):
--> 679     super().__setitem__(items, value)

File ~\Programme (portabel)\WPy64-31090\python-3.10.9.amd64\lib\site-packages\spectrochempy\core\dataset\baseobjects\ndarray.py:451, in NDArray.__setitem__(self, items, value)
    450 def __setitem__(self, items, value):
--> 451     keys = self._make_index(items)
    453     if isinstance(value, (bool, np.bool_, MaskedConstant)):
    454         # the mask is modified, not the data
    455         if value is MASKED:

File ~\Programme (portabel)\WPy64-31090\python-3.10.9.amd64\lib\site-packages\spectrochempy\core\dataset\baseobjects\ndarray.py:851, in NDArray._make_index(self, key)
    842         keys[axis] = self._get_slice(key, dim)
    844 # when the array is one-dimensional (squeeze_ndim=1 and shape[0]==1)
    845 # then we can consider that slicing is to be performed on the significant
    846 # axis (axis=-1)
    847 if (
    848     self._squeeze_ndim == 1
    849     and self.ndim == 2
    850     and self.shape[0] == 1
--> 851     and keys[0] != slice(None)
    852     and keys[0] != slice(0, 1, 1)
    853     and keys[1] == slice(None)
    854 ):
    855     keys.reverse()  # WARNING; assume 2D
    856 return tuple(keys)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### Anything else we need to know?

Maybe relevant: 
The involved spectra originate both from the same bruker spectrometer with similar but probably not exactly the same settings with respect to lower and upper wavelength and resolution. 

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'ISO8859-1')

 -- dev installation --
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[44], line 2
      1 spectra.remove_masks()
----> 2 scp.show_versions()

File ~\Programme (portabel)\WPy64-31090\python-3.10.9.amd64\lib\site-packages\spectrochempy\utils\print_versions.py:107, in show_versions(file)
    104 except FileNotFoundError:
    105     reqs = Path(__file__).parent.parent.parent / "requirements" / "requirements.txt"
--> 107 reqs = reqs.read_text().split("\n")
    108 for req in reqs:
    109     req = req.strip()

File ~\Programme (portabel)\WPy64-31090\python-3.10.9.amd64\lib\pathlib.py:1134, in Path.read_text(self, encoding, errors)
   1130 """
   1131 Open the file in text mode, read it, and close the file.
   1132 """
   1133 encoding = io.text_encoding(encoding)
-> 1134 with self.open(mode='r', encoding=encoding, errors=errors) as f:
   1135     return f.read()

File ~\Programme (portabel)\WPy64-31090\python-3.10.9.amd64\lib\pathlib.py:1119, in Path.open(self, mode, buffering, encoding, errors, newline)
   1117 if "b" not in mode:
   1118     encoding = io.text_encoding(encoding)
-> 1119 return self._accessor.open(self, mode, buffering, encoding, errors,
   1120                            newline)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\s...........XXXXXXX..........\\lib\\site-packages\\requirements\\requirements_dev.txt'

**Comment by atravert** [comment]
Thank you for your message. Unit tests and example related to `align` are still working fine with the  latest versions of scpy (see e.g. https://www.spectrochempy.fr/latest/userguide/processing/alignment.html)

Can you post or email me (arnaud.travert at unicaen.fr) the datasets you would like to align ? , this would be helpful for debuging, and i would use them for this unique purpose.

Thanks
Arnaud.

**Comment by atravert** [comment]
Can't repro

**Comment by atravert** [comment]
Can't repro
