### ISSUE TITLE
[FEATURE]: Convert any .srs file

### ISSUE THREAD

**Issue by mcurria** [spectrochempy/spectrochempy#769]
### Is your feature request related to a problem?

I am unable to read a `.srs` file using the `read_srs` function in SpectroChemPy. The file is not recognized, and I receive the following warning:

UserWarning: The reader is only implemented for Rapid Scan and High Speed Real Time srs files. If you think your file belongs to one of these types, or if you'd like an update of the reader to read your file type, please report the issue on https://github.com/spectrochempy/spectrochempy/issues

### Describe the solution you'd like

I expect the file to be read and a dataset to be returned.

**Comment by atravert** [comment]
Hello,

Thank you for your message. Can you post the  .srs file (or an equivalent ?). We will try to update the reader in a forthcoming release. 

Best,
Arnaud

**Comment by mcurria** [comment]
Not really, GitHub says it does not support the file type.

**Comment by atravert** [comment]
OK, then can you email me the file, or better a link to the file to : arnaud.travert at unicaen.fr ?

Thank you.

**Comment by atravert** [comment]
Hello,

The development version has been updated and now allows reading GC-type srs files (see #773). This will be intergrated in the next release. 

Best,
Arnaud
