### ISSUE TITLE
[Bug]: Google collab stopped working

### ISSUE THREAD

**Issue by MyonicS** [spectrochempy/spectrochempy#772]
### What happened?

I was trying to use spectrochempy in google collab, it worked a while back but now the runtime crashes when i try to install it. 
I tried the last three versions of scp, as well as a fallback version of google collab. I added logfiles of 2 of my attempts.
[output_scpinstall.log](https://github.com/user-attachments/files/16236179/output_scpinstall.log)
[output.log](https://github.com/user-attachments/files/16236180/output.log)

### Environment

Google collab

**Comment by atravert** [comment]
Hello, 

thank you for your message. Can you try the following ?:

```sh
!pip install pint==0.23 &>> output.txt
!pip install -q spectrochempy &>> output.txt
```

and then 
```python
import spectrochempy as scp
```
etc...

It works on my side, so let me know.
Best,
Arnaud.

**Comment by MyonicS** [comment]
That did the trick, many thanks for the quick reply!
