### ISSUE TITLE
[Bug]: import spectrochempy raise error in spyder 6.0

### ISSUE THREAD

**Issue by LeoRen1977** [spectrochempy/spectrochempy#778]
### What happened?

from spectrochempy import *
Traceback (most recent call last):

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\spectrochempy\api.py:116
    IP.run_line_magic("matplotlib", "widget")

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\IPython\core\interactiveshell.py:2480 in run_line_magic
    result = fn(*args, **kwargs)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\IPython\core\magics\pylab.py:103 in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\spyder_kernels\console\shell.py:96 in enable_matplotlib
    enabled_gui, backend = super().enable_matplotlib(gui)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\IPython\core\interactiveshell.py:3681 in enable_matplotlib
    configure_inline_support(self, backend)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\matplotlib_inline\backend_inline.py:205 in configure_inline_support
    select_figure_formats(shell, cfg.figure_formats, **cfg.print_figure_kwargs)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\IPython\core\pylabtools.py:297 in select_figure_formats
    raise ValueError("supported formats are: %s not %s" % (gs, bs))

ValueError: supported formats are: 'jpg','png2x','png','pdf','retina','jpeg','svg' not 'g','p','n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[3], line 1
    from spectrochempy import *

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\spectrochempy\__init__.py:79
    from spectrochempy import api

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\spectrochempy\api.py:118
    IP.run_line_magic("matplotlib", "qt")

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\IPython\core\interactiveshell.py:2480 in run_line_magic
    result = fn(*args, **kwargs)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\IPython\core\magics\pylab.py:103 in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\spyder_kernels\console\shell.py:96 in enable_matplotlib
    enabled_gui, backend = super().enable_matplotlib(gui)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\IPython\core\interactiveshell.py:3681 in enable_matplotlib
    configure_inline_support(self, backend)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\matplotlib_inline\backend_inline.py:205 in configure_inline_support
    select_figure_formats(shell, cfg.figure_formats, **cfg.print_figure_kwargs)

  File C:\ProgramData\anaconda3\envs\scpy\Lib\site-packages\IPython\core\pylabtools.py:297 in select_figure_formats
    raise ValueError("supported formats are: %s not %s" % (gs, bs))

ValueError: supported formats are: 'jpg','png2x','png','pdf','retina','jpeg','svg' not 'g','p','n'

### What did you expect to happen?

import spectrochempy in spyder like in ipython 

### Minimal Complete Verifiable Example

```python
from spectrochempy import *
```

### Environment

spyder 6.0
pip list
Package                       Version
----------------------------- --------------
aiohappyeyeballs              2.4.0
aiohttp                       3.10.5
aiosignal                     1.3.1
alabaster                     1.0.0
anyio                         3.7.1
archspec                      0.2.3
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
astroid                       3.2.4
asttokens                     2.4.1
asyncssh                      2.17.0
atomicwrites                  1.4.1
attrs                         24.2.0
autopep8                      2.0.4
Babel                         2.14.0
backports.tarfile             1.0.0
beautifulsoup4                4.12.3
binaryornot                   0.4.4
black                         24.8.0
bleach                        6.1.0
boltons                       24.0.0
Brotli                        1.1.0
brukeropusreader              1.3.9
certifi                       2024.8.30
cffconvert                    2.0.0
cffi                          1.17.1
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.2.2
conda                         24.7.1
conda-libmamba-solver         24.7.0
conda-package-handling        2.3.0
conda_package_streaming       0.10.0
contourpy                     1.3.0
cookiecutter                  2.6.0
cryptography                  43.0.1
cycler                        0.12.1
debugpy                       1.8.5
decorator                     5.1.1
defusedxml                    0.7.1
Deprecated                    1.2.14
diff-match-patch              20230430
dill                          0.3.8
distro                        1.9.0
docopt                        0.6.2
docrep                        0.3.2
docstring-to-markdown         0.15
docutils                      0.21.2
entrypoints                   0.4
exceptiongroup                1.2.2
executing                     2.1.0
fastjsonschema                2.20.0
flake8                        7.1.1
fonttools                     4.53.1
frozendict                    2.4.4
frozenlist                    1.4.1
gssapi                        1.8.3
h2                            4.1.0
hpack                         4.0.0
hyperframe                    6.0.1
idna                          3.10
imagesize                     1.4.1
importlib_metadata            8.5.0
importlib_resources           6.4.5
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.29.5
ipympl                        0.9.4
ipython                       8.27.0
ipython_genutils              0.2.0
ipywidgets                    8.0.4
isort                         5.13.2
jaraco.classes                3.4.0
jaraco.context                5.3.0
jaraco.functools              4.0.0
jedi                          0.19.1
jellyfish                     1.1.0
Jinja2                        3.1.4
joblib                        1.4.2
json5                         0.9.25
jsonpatch                     1.33
jsonpointer                   3.0.0
jsonschema                    3.2.0
jupyter_client                7.4.9
jupyter_core                  5.7.2
jupyter-events                0.6.3
jupyter-server                1.24.0
jupyterlab                    3.4.3
jupyterlab_pygments           0.3.0
jupyterlab_server             2.16.6
jupyterlab_widgets            3.0.13
keyring                       25.3.0
kiwisolver                    1.4.7
libmambapy                    1.5.9
llvmlite                      0.43.0
mamba                         1.5.9
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.9.2
matplotlib-inline             0.1.7
mccabe                        0.7.0
mdurl                         0.1.2
menuinst                      2.1.2
mistune                       3.0.2
more-itertools                10.5.0
multidict                     6.1.0
munkres                       1.1.4
mypy-extensions               1.0.0
nbclassic                     0.5.6
nbclient                      0.7.4
nbconvert                     7.16.4
nbformat                      5.10.4
nest_asyncio                  1.6.0
notebook                      6.5.7
notebook_shim                 0.2.4
numba                         0.60.0
numpy                         1.26.4
numpy-quaternion              2023.0.4
numpydoc                      1.8.0
osqp                          0.6.7.post0
packaging                     24.1
pandocfilters                 1.5.0
parso                         0.8.4
pathspec                      0.12.1
pexpect                       4.9.0
pickleshare                   0.7.5
pillow                        10.4.0
Pint                          0.23
pip                           24.2
platformdirs                  4.3.6
pluggy                        1.5.0
ply                           3.11
prometheus_client             0.20.0
prompt_toolkit                3.0.47
psutil                        6.0.0
ptyprocess                    0.7.0
pure_eval                     0.2.3
pybind11                      2.13.6
pycodestyle                   2.12.1
pyconify                      0.1.6
pycosat                       0.6.6
pycparser                     2.22
pydocstyle                    6.3.0
pyflakes                      3.2.0
PyGithub                      2.4.0
Pygments                      2.18.0
PyJWT                         2.9.0
pykwalify                     1.8.0
pylint                        3.2.7
pylint-venv                   3.0.3
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyOpenSSL                     24.2.1
pyparsing                     3.1.4
PyQt5                         5.15.9
PyQt5-sip                     12.12.2
PyQtWebEngine                 5.15.4
pyrsistent                    0.20.0
PySide6                       6.7.2
PySocks                       1.7.1
python-dateutil               2.9.0
python-json-logger            2.0.7
python-lsp-black              2.0.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.12.0
python-slugify                8.0.4
pytoolconfig                  1.2.5
pytz                          2024.2
pyuca                         1.2
pywin32                       306
pywin32-ctypes                0.2.3
pywinpty                      2.0.13
PyYAML                        6.0.2
pyzmq                         25.1.2
QDarkStyle                    3.2.3
qdldl                         0.1.7.post4
qstylizer                     0.2.3
QtAwesome                     1.3.1
qtconsole                     5.6.0
QtPy                          2.4.1
requests                      2.32.3
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.8.1
rope                          1.13.0
Rtree                         1.3.0
ruamel.yaml                   0.18.6
ruamel.yaml.clib              0.2.8
scikit-learn                  1.5.2
scipy                         1.14.1
Send2Trash                    1.8.3
setuptools                    74.1.2
setuptools-scm                8.1.0
shiboken6                     6.7.2
sip                           6.7.12
six                           1.16.0
sniffio                       1.3.1
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.5
spectrochempy                 0.6.9
Sphinx                        8.0.2
sphinxcontrib-applehelp       2.0.0
sphinxcontrib-devhelp         2.0.0
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 1.1.10
spyder                        6.0.0
spyder-kernels                3.0.0
stack-data                    0.6.2
superqt                       0.6.7
tabulate                      0.9.0
terminado                     0.18.1
text-unidecode                1.3
textdistance                  4.6.3
threadpoolctl                 3.5.0
three-merge                   0.1.1
tinycss2                      1.3.0
tmm                           0.1.8
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.13.2
tornado                       6.4.1
tqdm                          4.66.5
traitlets                     5.14.1
truststore                    0.9.2
types-python-dateutil         2.9.0.20240906
typing_extensions             4.12.2
tzdata                        2024.1
tzlocal                       5.2
ujson                         5.10.0
urllib3                       2.2.3
voila                         0.4.5
voila-material                0.4.3
watchdog                      5.0.2
wcwidth                       0.2.13
webencodings                  0.5.1
websocket-client              1.8.0
websockets                    13.0.1
whatthepatch                  1.0.6
wheel                         0.44.0
widgetsnbextension            4.0.5
win-inet-pton                 1.1.0
wrapt                         1.16.0
xlrd                          2.0.1
yapf                          0.40.1
yarl                          1.9.4
zipp                          3.20.2
zstandard                     0.23.0

**Comment by fernandezc** [comment]
Hi,
Do you get this error if you use the recommended way of importing Spectrochempy,  i.e., `import spectrochempy as scp`?
