### ISSUE TITLE
[Bug]: deprecation error with scipy>=1.14

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#780]
### What happened?

scipy.integrate.{simps,trapz,cumtrapz} have been removed in scipy 1.14 in favour of simpson, trapezoid, and cumulative_trapezoid. The spectrochempy code should be corrected 

### Environment

_

**Comment by fernandezc** [comment]
Hi Arnaud. It seems to me that this was already fixed sometimes ago in the integrate module. https://github.com/spectrochempy/spectrochempy/blob/master/spectrochempy/analysis/integration/integrate.py.

**Comment by atravert** [comment]
Hi Christrian,

Yes this puzzled me as well, but the bug was reported by a student who 
just intalled scpy. I will check with her again !


Le 25/10/2024 à 10:14, Christian Fernandez a écrit :
