### ISSUE TITLE
Documentation improvement: user guide and tutorials

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#95]
The user guide and tutorials actually play very similar roles. Should we make them more differents (user guide: more technical ; tutorials more pedagogical/scientific ?; 

if not, I suggest the following:

1. clean-up current user guide pages 
2. merge tutorials in a single section "user guide" 
3. Create a section "case studies" where literature examples (essentially from LCS from the moment) would be reproduced  

What do you think @fernandezc ?

**Comment by fernandezc** [comment]
> The user guide and tutorials actually play very similar roles. Shjoumld we make tyhem more differents (user guide: more technical ; tutorials more pedagigical ?;
> 
> if not I suggest the following:
> 
> clean-up current user guide pages
> merge both in a single section "user guide"
> Create a section "case studies" where literature examples (essentially from LCS from the moment) would be reproduced
1,2 and 3. are OK with me !

**Comment by fernandezc** [comment]
I started merging the user guide and tutorials by reworking the documentation. When this is done, I will put the table of contents on the WIKI so that we can propose changes, reorganizations, etc. 

The "API reference" is also undergoing a complete reorganization at the same time.
